### ISSUE TITLE
CLA test should report details of failures

### ISSUE THREAD

**Issue by jberkus** [communitybridge/easycla#1047]
## Summary

Like other presubmit tests, the CLA test should report a log of all failures.  This would enable many users to self-service in fixing their CLA problems.

## Background

Currently, the CLA presubmit test is essentially pass/fail.  It tells the submitter if they "passed" the CLA test, or if they didn't, but it doesn't tell them why they failed; the "details" link just links to the general troubleshooting guide.  The only way to get details of the failure is for the contributor to open a ServiceDesk ticket, which is both slow and frustrating (and consumes a lot of staff time).

For example, one contributor got the attached error, saying " cla/linuxfoundation — dkypuros authorized, but 1 other problem".  However, the test doesn't report back what the "one other problem" is, and clicking on the details link just sends the contributor to the general "maybe your email address isn't linked to your GH account or maybe it's not linked to your LF account, or maybe something else" troubleshooting guide.  For a contributor who believes that they have followed all of the steps in the guide already, this is intensely frustrating.

Compare this with the test logs the Netlify tests give you, which go through step-by-step which things passed and which failed and why.  This is what *should* appear when the contributor clicks "details" for the failed CLA test.

![Screenshot from 2020-05-04 10-50-56](https://user-images.githubusercontent.com/115146/81006280-16b20400-8e04-11ea-8373-538a7ebabb66.png)

**Comment by WillsonHG** [comment]
Closing this issue because the cla bot you are referring to is the older CLA system and is not from the new EasyCLA system that this team develops. 

Also, the "details" link pictured above goes directly to a GitHub article which directly addresses the specific issue in that PR - the commit user does not match the user who signed the CLA. The article gives details to the user about how to fix this, usually requiring them to change the email address in their git settings.

EasyCLA also has a comment and a link to the same github article when this problem happens, so this enhancement has already been added for the product.

**Comment by jberkus** [comment]
It sounds like you're saying that EasyCLA doesn't fix this issue because you don't think it's an issue at all.

**Comment by WillsonHG** [comment]
Hi @jberkus 
As I understand it, the issue is that it wasn't clear enough in the messaging from the other cla bot check that the user id was wrong in the commit. The user in question didn't realize the link given in the details was the solution to the problem he was having. 

For EasyCLA, we try to make the bot comments very specific. When it sees that the user on the commit isn't linked to a github account, the bot will make this comment in the PR that calls out this situation as shown below

![image](https://user-images.githubusercontent.com/46732999/81089137-f8aed700-8ec9-11ea-9993-624eb4d7f504.png)

**Comment by jberkus** [comment]
Aha!  Thank you, yeah, that's what I'm looking for.  Wish we had it in the old system.

/resolved

**Comment by jberkus** [comment]
BTW, for user story, the real problem was more like this:

1. User gets CLA failure
2. Follows link to the "linking your PR to your ID" instructions
3. Follows instructions (he believes)
4. PR still rejected
5. User confused, goes to me for help

What was happening with his PR was that he'd accidentally merged in an upstream commit from another branch that wasn't linked.  But without detailed feedback like easyCLA gives, he couldn't ever diagnose that.
