### ISSUE TITLE
Table 1 - No CLA Manager Designee Assigned - Step 2.2 in PRD

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1103]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Db3d69b699313a6e8106fdb78dea2b182)for the corporate console for EasyCLA.

Step 2.2 in Table 1 of PRD 
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

![image](https://user-images.githubusercontent.com/57362064/81769326-f2f55a80-94a2-11ea-8b16-57adf0647b50.png)

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by nirupamav** [comment]
@dealako @pranab-bajpai 
Could you please clarify below query
As per PRD, the project/foundation name is displayed if the CLA is signed for the project/foundation
But Endpoint returns CLA Groups for the foundation/project. So if there are say 4 CLA groups's signed for the project/foundation, 4 rows with same project/foundation name is displayed. Are we supposed to display CLA group name in UI? I am not able to understand the requirement

Observed below issues
1. 401 is returned instead of 404 when invalid Company SFID is provided, 
2. 400 is returned instead of 404 when invalid ProjectSFID is provided
3. 403 is returned instead of 404 when projectSFID or CompanySFID is not provided or when both are not provided

**Comment by nirupamav** [comment]
@pranab-bajpai 
Could you please clarify the below
cla-manager (clamanager1devintel) has access to below data
![image](https://user-images.githubusercontent.com/60865903/83169317-7dd78580-a130-11ea-863d-6a7e0887d188.png)
And when the cla-manager is trying to fetch CLA's for Brigade project which is under CNCF and cla-manager does not have access to CNCF, data is fetched for the project. Is this expected behavior?
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000015vpjXAAQ/project/a092M00001IV4PgQAL/cla
![image](https://user-images.githubusercontent.com/60865903/83169545-ce4ee300-a130-11ea-88e6-2087208e06a5.png)

**Comment by prasannamahajan** [comment]
> @dealako @pranab-bajpai
> Could you please clarify below query
> As per PRD, the project/foundation name is displayed if the CLA is signed for the project/foundation
> But Endpoint returns CLA Groups for the foundation/project. So if there are say 4 CLA groups's signed for the project/foundation, 4 rows with same project/foundation name is displayed. Are we supposed to display CLA group name in UI? I am not able to understand the requirement
> 
> Observed below issues
> 
> 1. 401 is returned instead of 404 when invalid Company SFID is provided,
> 2. 400 is returned instead of 404 when invalid ProjectSFID is provided
> 3. 403 is returned instead of 404 when projectSFID or CompanySFID is not provided or when both are not provided

As Discussed with @nirupamav 
We have decided that we will return 403 if user does not have access of the project/company

**Comment by vinod-kadam** [comment]
As updated by Prasanna, this API is already available for integration.

**Comment by nirupamav** [comment]
**Tested and observed below issues**
1. Empty values are returned for all fields in signed_cla_list object. Signature exists for the cla group and also the user I used is cla-manager for the cla group
![image](https://user-images.githubusercontent.com/60865903/83753369-c38fd300-a687-11ea-8cdd-89e93ed0c1e4.png)
2.When invalid projectsfId is provided 404 should be returned, but 403 is returned
3. When invalid companysfId is provided 404 should be returned, but 400 is returned with below response
{
    "Message": "project not found"
}
4. When projectsfId/companysfid is not provided 400 should be returned, but 403 is returned
5.
