### ISSUE TITLE
Table 1 - No CLA Manager Designee Assigned - Step 2.3.2 in PRD

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1106]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Db3d69b699313a6e8106fdb78dea2b182)for the corporate console for EasyCLA.
![image](https://user-images.githubusercontent.com/57362064/81770563-45844600-94a6-11ea-9da3-5fa1b59f5827.png)

Step 2.3.2 in Table 1 of PRD 
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by nirupamav** [comment]
Testing is performed in #1104 as both tickets use same endpoint

**Comment by vinod-kadam** [comment]
@prasannamahajan , please update us on the status of this ticket? If it is still work in progress then please provide ETA; else please update the status of the ticket.

**Comment by prasannamahajan** [comment]
We have found multiple issue for this
1) cla-signatory was not added properly (fixed, PR not raised yet)
2) user should be created automatically (fixed, PR not raised yet)
3) easycla v1 is not accepting token generated by lfx-ui (not yet fixed. I am in discussion with david about this. Will fix it after that)

**Comment by vinod-kadam** [comment]
As updated by Prasanna, this API will be available for integration on 4th Jun. As soon as it is ready for integration, Prasanna will update lfx team over slack channel.

**Comment by dealako** [comment]
LFX team should be unblocked now. Notified Tejas and Ahmed via Slack.

We are working on a use-case where the org service is not returning the scopes as we expect. Investigating...

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
Followed the API doc and tried with different payload, but always 400 response with below message is displayed. No able to proceed with testing due to this issue
{
    "Message": "json: cannot unmarshal string into Go value of type sign.requestCorporateSignatureOutput"
}
**API DOC** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/requestCorporateSignature

**Payload1 (For send_as_email followed format provided in API doc )**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ce17bfd-a869-4d20-9252-8eea517ea41e)

**Payload2**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/81f4cd68-c0a6-4422-9918-ecc3c1c20c60)

**Payload3**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c7a783eb-d44b-4ab6-a310-48a3cb933bb2)

**Payload4**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/025a46d1-f2f0-4e64-91f9-b5a8a88bf561)

**Comment by prasannamahajan** [comment]
@nirupamav fixed all the unmarshal error
instead it will return 400 with error returned from v1 api in response body.

**Comment by nirupamav** [comment]
Tested in https://github.com/communitybridge/easycla/issues/1104 and hence moving the ticket to QA Done
