### ISSUE TITLE
Table 1 - No CLA Manager Designee Assigned - Step 3 in PRD 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1107]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Db3d69b699313a6e8106fdb78dea2b182)for the corporate console for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/81770827-01457580-94a7-11ea-858a-85971e449792.png)

Step 3 in Table 1 of PRD 
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by vinod-kadam** [comment]
@wanyaland Please provide the updates on this ticket. Also please provide the ETA if the ticket is still in progress.

**Comment by wanyaland** [comment]
Hello @vinod-kadam . The ETA for this is tomorrow it shall be done.

**Comment by vinod-kadam** [comment]
@wanyaland any update? ETA for this API was yesterday.

cc @dealako

**Comment by pranab-bajpai** [comment]
@wanyaland please work with @dealako to get those urls.

**Comment by vinod-kadam** [comment]
As discussed in the standup. please complete the API work by using below Portal URLs:
Dev Env:
https://lfx.dev.platform.linuxfoundation.org
Staging Env:
https://lfx.staging.platform.linuxfoundation.org
PROD Env:
https://lfx.platform.linuxfoundation.org

& provide the API to LFx team for integration.
Once you get Project EasyCLA specific URLs from "ahmed.abdulmoniem@andela.com" <ahmed.abdulmoniem@andela.com> then you can update the email section.
Please contact Ahmed for Project EasyCLA specific URLs.

**Comment by wanyaland** [comment]
@vinod-kadam  Updated path parameters and shall merge once approved

**Comment by wanyaland** [comment]
Happy paths tested and can be integrated with Lfx

**Comment by nirupamav** [comment]
Testing InProgress. Will keep updating issues
1. Wrong email is sent when CLA Manager request is sent
![image](https://user-images.githubusercontent.com/60865903/83884957-4b96db00-a763-11ea-9752-61187213cfc2.png)

**Comment by nirupamav** [comment]
@pranab-bajpai 
Could you please clarify below queries
1. Will user with below roles have access to the screen Table1, Step1 when user access to organization and cla is not signed for the project

> cla-manager
> cla-signatory
> cla-manager-designee
> company-admin
> company-owner
> company-alternate-owner
> contributor
> Please let me know if I missed any roles

2. In Table1, Step3, if any of the role above identifies cla manager, 

- User with what roles can be identified as cla-manager
- Say a user1 is cla-manager for Intel & OpenColorIO and user2 is company-admin and identified user1 as cla-manager for Intel & OpenCue, since user1 already has cla-manager role, should only scope for the project be added wtithout assigning the cla-maanger-designee role
- Now say as a contributor if I come to Step3 and identify some other contributor as cla-manager, then other contributor is given cla-manager-designee role. I am not sure if this happens in real time but should this be allowed?

**Comment by nirupamav** [comment]
@wanyaland 
**Issue1**
Observed that this is working when the logged in user has access only to project. Actually any user who is associated to the organization can view all the projects and also try to be CLA Manager or identify CLA Manager. Below is the scenario I tried

Role - user
scope - Community
Role - contributor
scope - Brigade|Bakbone (Project|Organization)
Failed with 403
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1bd65741-be2b-4357-a8e8-5b8715b89f1a)

Then added scope for the project for which I was trying to identify CLA Manager
scope - CloudEvents|Bakbone (Project|Organization)
Passed with 200
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4b7e9f73-aa30-413b-908d-a726142409db)

I think the user who is trying to identify the CLA Manager need not have access to the project

**Issue2**
Observed that still wrong email is sent to the identified CLA Manager
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e92d6d34-91f3-4d17-9333-8a35e22ac931)

**Issue3**
When there is no company admin for the Organization still API response is 204 and there is no validation to check if company admin exists

**Query**
As of now 3 company admin's can be added to the organization from LFX portal. So when we contact admin, is the email sent to all the 3 admins

**Comment by wanyaland** [comment]
@nirupamav 
Issue1: For scope..a user needs to have organization scope and that can work as long as the organization scope is set for the given ID
issue2, Issue 4: @pranab-bajpai  can confirm on email content. I used the templates from PRD for this ticket. 
Updated issue 3 and shall raise a PR

**Comment by dealako** [comment]
Moved to next sprint.

**Comment by nirupamav** [comment]
Tested an observed below issues
**1. Able to contact admin/assign cla-manager-designee from API to already signed project**
**2. The link to create LFID is still pointing to https://identity.linuxfoundation.org/ instead of myprofile link. Issue is tracked in Bug #1304**
**3. Email of the CLA Manager Designee is not displayed in the email sent to create LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1fdec1cb-f988-4fa3-b05e-f2c06b30a373)
**4. We are contacting the admin to sign CLA or to assign cla-manager-designee, but the email content says that contributor would like to contribute which is not what we are doing in the flow. Email content needs to be changed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/07e7c6cf-5959-42b2-87ea-e26eaaa9f539)

**5. fullname field accepts more than 60 characters. As by comments in https://jira.linuxfoundation.org/browse/LFX-1914, fields should accept 60 characters**

**Comment by nirupamav** [comment]
**_Verified that below issues are fixed_**
**5. fullname field does not accept more than 60 characters and 422 is returned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/673011be-4463-41e6-8f89-1328a141b930)

**7. Not bble to send request when only spaces is provided for fullname field and 422 is returned which is as expected**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3b4a21d6-906e-43f6-b489-0c22317e96ca)

**8. 422 with appropriate message is returned when invalid email is provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/13cd62a3-e6a1-417f-bb33-bafa603aca83)

**Comment by nirupamav** [comment]
**_Observed below issues and issues 1,2,3,4,6,9,10,11 could not be verified due below mentioned Issue 13_** 

**12. Space in not allowed between names in full name field. User should be able to enter space between firstname and lastname**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ec2fcce8-c58f-4b62-915a-2e5a44403fdd)

**13. Observed that "project already signed" is returned even when there is no signature. Not sure if this is related to delete cla group, But just letting know the scenario I tried. For the projects that I am trying I had deleted CLA group and again trying to sign CLA with new CLA group created for the project**

[Uploading... image.png ]

**Comment by nirupamav** [comment]
**_Verified that the issue is fixed_**

**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000018BhtKAAS/project/a091700000AGJ5EAAX/cla-manager-designee**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/934bdf03-f46f-436f-aaa7-83a3c49c64dd)

**Comment by nirupamav** [comment]
**_Observed few issues and logged below tickets to track the issues and listed few issues in this ticket itself_**
#1664, #1665, #1666

**1. Able to send request when full name is not provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4a93a7dd-47cc-46ef-925b-a006b852b7ad)

**2. Able to send request when only spaces is provided for fullname field**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c15a0544-5ecc-41d2-b1f8-0660271b3bd9)

**3, 404 is returned instead of 400 with appropriate message when invalid email is provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c4f554f2-00e4-4879-826c-0b227a090df7)

**4. Able to send request when fullname field is not provided in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/de6cc0fd-2a4b-48e7-afbc-32f0811e10a5)

**Comment by nirupamav** [comment]
Blcoked due to #1761 as always 504 response is returned

**Comment by nirupamav** [comment]
**_Issues are still reproducible_**

**1. Able to send request when full name is not provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/abe4b4aa-6dc7-40af-8953-03891df24694)

**2. Able to send request when only spaces is provided for fullname field**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/946647ec-a9dd-44cd-9966-412835e17f0a)

**3. 202 is returned instead of 400 with appropriate message when invalid email is provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/57a94f48-b44c-4cd2-8e10-bedb949bb88b)

**4. Able to send request when fullname field is not provided in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7d1968d1-0bde-4aeb-9058-e6b9c481f3e3)

**Comment by nirupamav** [comment]
Verified that all the issues are fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fb173f79-1ee8-44a5-b93b-3cf04c2d58d6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6b1b0978-ac1d-446c-86c1-1f96d1c42348)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0f824b12-9fd5-4b61-8e5a-663b45f2ce63)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/46a0ac95-deed-4e74-bc50-7200c8b01fa7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/783cf8bf-fb77-43b8-b6fd-79d828b20131)
