### ISSUE TITLE
v2 Project Console - Fetch Templates

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1145]
## Summary

Provide API to fetch CLA Templates.

## Background

Provide v2 API to fetch CLA templates and to generate PDFs, including a sample without an existing CLA Group, role: CLA Manager.

[PRD reference](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2), Table 1, step 2b.1

![image](https://user-images.githubusercontent.com/519609/83200977-5addaf00-a0f9-11ea-8555-a6c4353f4ebb.png)

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
1. Observed that user with LFID having any role is able to access endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/template
**Tested with below roles**
company-admin role 
only user role
mentee role

2.Observed that user with LFID having any role is able to access endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/template/preview?template_for=ccla
**Tested with below roles**
company-admin role 
only user role
mentee role

3. Observed that 422 is returned instead of 400 when query parameter is not provided or when invalid value is provided for the query parameter
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5046bd73-ae0d-464c-a524-9a0811206efc)

4. Observed that invalid pdf file is generated with 400 response and no error message in response when empty payload is provided or when invalid payload is provided
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aa4e3d99-fc8c-4e38-9043-96034df03f13)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4ef801a9-0b7f-4dd4-8f4f-c2454d1b1a84)

**Comment by prasannamahajan** [comment]
@nirupamav 
**Point 1 and Point 2**:  Observed that user with LFID having any role is able to access endpoint
Change Done: restricting api for project-manager role only
**Point 3**: Observed that 422 is returned instead of 400 when query parameter is not provided or when invalid value is provided for the query parameter
Comment: This response code is return by swagger generated client. we can not change that.
**Point 4**: Observed that invalid pdf file is generated with 400 response and no error message in response when empty payload is provided or when invalid payload is provided
Change Done: on error, api will return json response with error message.

**Comment by nirupamav** [comment]
Tested and observer that Issue1,2 and 4 are fixed and working as expected
As per comments above by dev team, for Issue3, 422 is returned by swagger and cannot be changed. Hence moving the ticket to QA Done

@pranab-bajpai 
Testing is completed. Could you please review the test plan and let me know if I missed any scenarios
https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Get+Templates+Test+Plan
https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Template+Preview+Test+Plan
