### ISSUE TITLE
v2 Project Console 

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1147]
## Summary

Add api to create cla group (PRD table 1 step 2c)
Add api to get cla groups list for foundation (PRD table 1 step 1)
Add api to enroll projects into cla_group (PRD table 1 step 3d)
Add api to delete cla_group

## Background

Provide v2 API to Get, Create, Update, Delete CLA Groups

[PRD reference](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2), Table 1, step 2c, step 3d

![image](https://user-images.githubusercontent.com/519609/83200977-5addaf00-a0f9-11ea-8555-a6c4353f4ebb.png)

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.
1. Backend API needs to make sure that a project cannot be added to another CLA Group if it is already there, so if a project is already in a CLA Group it should show up greyed out.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by pranab-bajpai** [comment]
@prasannamahajan Backend API needs to make sure that a project cannot be added to another CLA Group if it is already there, so if a project is already in a CLA Group it should show up greyed out.

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**Create CLA Group**
1. Foundation name and Project name is not returned in the response after CLA Group is created
![image](https://user-images.githubusercontent.com/60865903/86765134-657b5480-c066-11ea-8005-adba8f95b45b.png)

2. 500 Internal Server Error is returned instead of 400 when trying to create CLA group name with empty CLA group name or when trying to create CLA group without providing the cla_group_name field in the payload
![image](https://user-images.githubusercontent.com/60865903/86769051-2223e480-c06c-11ea-8cab-a7f8a2706148.png)

3. Able to create CLA group with CLA group name having only spaces
![image](https://user-images.githubusercontent.com/60865903/86769170-5c8d8180-c06c-11ea-8b46-b26547d40c80.png)

4. When trying to create CLA group with already enrolled projects, only one project sfid is returned in the response indicating it is already enrolled. Since only one projectID is returned, in UI user has uncheck that and try again. So user has to keep repeating it until all projects that are already enrolled are removed. So in the response all projects that are already enrolled should be returned so that user can uncheck all those projects and then try to create CLA group
![image](https://user-images.githubusercontent.com/60865903/86769783-521fb780-c06d-11ea-84ef-c37ae1406dad.png)

5. 500 is returned instead of 400 when invalid template Id is provided
![image](https://user-images.githubusercontent.com/60865903/86773267-138cfb80-c073-11ea-8989-aa72c119c0f4.png)

6. Not able to create CLA Group at foundation level for a foundation which does not have any projects, as endpoint expects to provide both foundationsfid and projectsfid for e.g. Civil Infrastructure Platform (Civil Infrastructure Platform)

**Comment by prasannamahajan** [comment]
@nirupamav 
3. _Able to create CLA group with CLA group name having only spaces_
Q : @dealako  What is criteria of acceptable cla group name ? 
4. _When trying to create CLA group with already enrolled projects, only one project sfid is returned in the response indicating it is already enrolled. Since only one projectID is returned, in UI user has uncheck that and try again. So user has to keep repeating it until all projects that are already enrolled are removed. So in the response all projects that are already enrolled should be returned so that user can uncheck all those projects and then try to create CLA group_
A: UI should not pass already enrolled projects to the API itself. From UI, already enrolled projects should be greyed out.

**Comment by nirupamav** [comment]
**_Tested and observed that few issues are still reproducible and also observed new issues for Create CLA Group_**

**2. 500 Internal Server Error is returned instead of 400 when trying to create CLA group name with empty CLA group name or when trying to create CLA group without providing the cla_group_name field in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6e20fdd3-8fc9-4156-adac-6fe539ac9a20)

**5. 500 is returned instead of 400 when invalid template Id is provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fa511066-71d2-4adf-84cd-21e69d4a6f09)

**8. Able to create CLA group with CLA Group name and description having <3 and >256 characters. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/validateClaGroup accepts min:3 and max:256 for both cla group name and description and the same validation should be applied for create cla group endpoint**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/731ff86b-cdf2-4b43-94fb-61518f248468)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6413fa31-f822-4d5a-8db3-1beb3880a6fc)

**9. 500 Internal Server Error is displayed when trying to creating cla group for already enrolled project. This is happening when cla group is being created with only foundationsfid**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/322b912e-1836-44c0-bfee-9bc748f8c724)

**10. 500 is returned with error message for project_sfdi when no value is provided for foundaion_sfid. 400 with appropriate message should be returned. This is happening when cla group is being created with only foundationsfid**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ee48d895-b099-43be-b216-05bcab189f10)

**11. 500 is returned when invalid foundation_sfid is provided. 400 should be returned. This is happening when cla group is being created with only foundationsfid**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d4f18ab2-5e90-4520-bd10-f7e54a22decd)

**Comment by prasannamahajan** [comment]
@nirupamav 
I have fixed all the bugs mentioned above.
Note : API will return 422 response code, If one of validation mentioned in swagger spec fails.

**Comment by nirupamav** [comment]
**_Verified and observed that the issues are fixed_**
**2. 422 status with appropriate error message is returned when no value is provided for cla_group_name or when cla-group_name is not provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e1972c8f-dd78-4896-b12e-87e3a0710fee)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1d9ddd56-76aa-4e6e-ba6f-0b14fc42f878)

**5. 400 with appropriate error message is returned when template id is invalid**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/00b7ff56-20cb-43f3-9542-6a2dd5fdd3b1)

**Comment by nirupamav** [comment]
**_12. Deletion of CLA Group_**

**Before**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/493e387a-bd32-4e98-81b0-74ee77a137d6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2963684e-16b8-445d-b9bd-13d37886f231)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5cc94cea-a4c8-46d4-a44e-d78f5e61d2e4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d86310f9-4096-499b-b68d-2cc5712f1e0d)

**After**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4cbae501-ef9a-4a22-8a9d-862a76d89601)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/05ea7bb5-b6d0-4e2d-ab74-00d1c0545866)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b688a138-09ec-4a42-9acd-21ced071514e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/78d10114-28a6-4ce5-bddf-301470d2dc7d)
