### ISSUE TITLE
Download all Individual Signatures for this CLA Group as CSV

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1229]
## Summary

Download all Individual Signature details for this CLA Group as a CSV file.

## Background

For a description of the services needed, view the [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2).

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2)

**Comment by nirupamav** [comment]
**_Tested and observed except Date no other data is downloaded_**
**CLA Group with both CCLA and ICLA Enabled and Employee also needs to sign ICLA
Created this CLA group today and signed CLA today i.e. 9-Jul-2020**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f2bda8ad-9281-4ca1-a0be-499a37741c60)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a6a1be71-e126-4dce-a9cf-405bbfbdce2a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3fad984c-f0fc-414b-9253-ef8fcad8a9a6)

**Comment by nirupamav** [comment]
**Tested and observed that Issue2 is still reproducible. 200 reponse with empty file is returned instead of 400 for CLA group with only CCLA enabled**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/83c348d3-25c4-4489-acac-c9e972830738/icla/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b52da480-9096-47f4-988e-24e264f0b730)

**Observed that Issue1 is fixed. Also as per discussion with @pranab-bajpai data need not be sorted and hence Issue3 is invalid**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ba265b9d-6555-46f8-81cf-027037ee48df)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7c86f3f5-3d34-46ad-9e14-082bc519d52e)

**Comment by nirupamav** [comment]
**Tested and observed that Issue2 is still reproducible. 200 reponse with empty file is returned instead of 400 for CLA group with only CCLA enabled**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/ab7b30ee-e813-428f-bc68-3b1022cfb8f6/icla/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a75e4047-82b1-4214-b52c-1e06560a0bb0)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ebc20fd4-6cfa-42ab-bb3e-9d5683f78317)

**Comment by dealako** [comment]
@nirupamav can you re-test the last comment you made. We have updated the permissions and error handling recently, [see this bit of logic](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/v2/signatures/handlers.go#L978-L982).

**Comment by nirupamav** [comment]
Tested and observed below issues
1. 500 is returned when invalid cla group id is provided
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c5abf8b5-a41a-45fe-a095-565cb437b131)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/304968cb-c86c-4b89-8426-bb3a579c733c)
