### ISSUE TITLE
Download all Employee Signatures for this CLA Group and company as a CSV file

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1233]
## Summary

Download all Employee Signatures for this CLA Group and company as a CSV file

## Background

For a description of the services needed, view the [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2).

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2)
- [Wireframe image] https://confluence.linuxfoundation.org/pages/viewpage.action?spaceKey=PROD&title=Project+Console+for+EasyCLA+V2&preview=/47580018/51578684/image2020-6-23_22-56-14.png

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**

**1. 200 with empty file is returned for CLA group that is only ICLA enabled**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/ab7b30ee-e813-428f-bc68-3b1022cfb8f6/company/0014100000Te0iaAAB/employee/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/55902967-b48a-4080-a182-539a9edfeaad)

**2. 200 with empty file is returned for CLA group that is CCLA enabled but has not signed CLA for the company that is provided in the endpoint**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/ab7b30ee-e813-428f-bc68-3b1022cfb8f6/company/0014100000Te0iaAAB/employee/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4582799d-64e0-448b-b8c9-93d6ede3c1bc)

**3. 500 Internal server error is returned instead of 400 when invalid companyId is provided in the endpoint**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/60312f56-7a67-45d4-9593-d37f6dda0c71/company/a092M00001IfR9gQAF/employee/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/416a4440-598b-4563-bfbe-0d7b1de39c38)

**Comment by nirupamav** [comment]
Verified that the issues are fixed

**1. 404 with appropriate message is returned for CLA group that is only ICLA enabled**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/0d36e056-b824-4339-b751-c6e60b6b1dd8/company/0014100000Te0iaAAB/employee/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a8492cb1-48ec-4660-8669-05842933db3c)

**2. 404 with appropriate message is returned for CLA group that is CCLA enabled but has not signed CLA for the company that is provided in the endpoint**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/4fbc1fb3-24a7-4d71-9f20-4e2a0f342610/company/0014100000Te0iaAAB/employee/csv
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/70556f59-ee36-40cc-815a-04da83a2f575)

**3. 404 with appropriate message is returned when invalid companyId is provided in the endpoint**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eac8219d-ab91-4220-b113-2696de2de2db)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2e98910b-da47-4b6e-a1d8-12ca09ccf866)
