### ISSUE TITLE
Get Events by Foundation SFDC

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1237]
## Summary

Get Events by Foundation SFDC

## Background

Fetch events by FoundationSFDC.

See [PRD table 1 step 3](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2#ProjectConsoleforEasyCLAV2-Table1.CLASetupforaFoundation(CNCF)).

## User Story

As a project manager, I want to see the events for the CLA Group at the foundation level.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2#ProjectConsoleforEasyCLAV2-Table1.CLASetupforaFoundation(CNCF))

**Comment by dealako** [comment]
Added PR for the Swagger: https://github.com/communitybridge/easycla/pull/1238

**Comment by dealako** [comment]
Depoyed Swagger spec to DEV - need to complete the repository impl and confirm CSV writer works.

**Comment by prasannamahajan** [comment]
API: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getFoundationEvents

**Comment by nirupamav** [comment]
**Tested and observed below issues**
**Endpoint** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/events/foundation/a0941000005osNmAAI
1. Observed that few events were not fetched. Tried below actions and they were not fetched in events. 
- Delete CLA group
- Add github username in approval list
- Individual contribution ICLA signature
- Corporate contribution ICLA signature
@pranab-bajpai @dealako Could you please me know what all events are fetched by this endpoint

2. For event type "UserAssociatedWithCompany" below is the event data where None is displayed instead of user details. Also is this even when contributor is added to approval list? If it is different which event is this?
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0250b7b6-62a8-45ab-8b3c-3bef12f8127e)

3. For event type "cla_manager.added" observed that company name and project name is not displayed in event data 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/28c024d2-2bb8-474b-9fb1-df71ba6ae19e)

4. Also when CLA group is created even data mentions it as project created
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b3fd88d5-8efe-442c-abd8-cd6e9d1b10de)

5. When CCLA is signed by CLA Manager the event is displayed as EmployeeSignature. Doesn't employee signature mean ICLA signature by employee?
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d9fd565b-585d-43c4-99c3-13ef5617b731)

**Comment by dealako** [comment]
@nirupamav thanks so much for reviewing the above.
- Regarding #1
  - CLAMangerDelted event looks to be configured correctly via [this bit of code](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/cla_manager/service.go#L352)
  - Add GitHub username to the approval list is configured to log the even per [this bit of code](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/signatures/service.go#L663). All the events relating to the approval list should be generated from this function. Type is: `cla_manager.approval_list_updated`
  - Updated event code for ICLA and CCLA signature signing
- Resolved #2 added additional details/parameters
- Resolved #3 item above, parameters were not provided to event logger
- Resolved #4 updated text
- Resolved #5: ICLA is individual, CCLA is slang for both Corporate CLA signed by CLA Manager and Employee Signature.  But, in this case you are mentioning it is the CLA document signed by the signatory.  I have updated the event logging logic to account for logging all events.

[Here's the PR](https://github.com/communitybridge/easycla/pull/1358)

**Comment by dealako** [comment]
Deployed to DEV.

**Comment by nirupamav** [comment]
Will test when all Project console endpoints are ready for testing

**Comment by nirupamav** [comment]
**_Tested and observed below issues
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/events/foundation/a0941000002wBzCAAU_**

**1. When CLA is signed by Signatory still the even is logged as EmployeeSignatureSigned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/59dbba78-6c0c-43df-a138-88b24bc7b9d1)

**2. When github org is added to the project event is not logged**

**3. Company name is undefined for event when Individual Contributor signs ICLA for the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/703bbe82-f23b-4b21-8883-49010fc97dda)

**4. Observed that the time when PR was raised is used instead of the time when contributor was acknowledged. Due to this event of adding the contributor is displayed after the even of the employee signature**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/91ec74bf-d8fb-4880-8533-0d97d6d2c364)

**5. Observed that time when first PR raised is displayed for ICLA which was signed later**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/732cbc07-c4b2-453a-882f-d9607cff0ead)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/29662caf-14f9-45db-a3cd-e73f7e283034)

**6. User None is displayed for both Individual and Employee signature events**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e5a268fc-6211-4918-b469-ba15689ba3a9)

**Comment by dealako** [comment]
Remove duplicate information from message is already in one of the fields.

**Comment by dealako** [comment]
Also see note from @aegixx:

Really minor bug, when an individual signs an ICLA, company name on the Event gets set to "undefined" instead of just being left out:
```
EventCompanyName:"undefined"
EventData:"individual signature of user Bryan Stone signed for project 20200812 CLA Test"
EventFoundationSFID:"a092M00001IV7AiQAL"
EventID:"779ec43b-10f3-48da-abf3-c8c4f621f3c8"
EventProjectExternalID:"a092M00001IV7AiQAL"
EventProjectID:"0fa4e4f5-de60-4908-afe0-24a5ae9378d2"
EventProjectName:"20200812 CLA Test"
EventProjectSFID:"a092M00001IV7AiQAL"
EventProjectSFName:"EasyCLA"
EventTime:"2020-08-12T19:38:53.882276+0000"
EventTimeEpoch:1597261133
EventType:"IndividualSignatureSigned"
UserID:"45d29ec6-78a0-4eae-9915-5707622c4350"
UserName:"Bryan Stone"
NextKey
```

**Comment by rinkeshbhutwala** [comment]
@dealako I have verified this ticket and found that all the events are coming from the python side and over there we have checked **if the user is empty then we have set it as None**

**Comment by vinod-kadam** [comment]
Corresponding LFX ticket for this one is LFX-2113.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland, he raised a PR yesterday & it has been merged so available for testing on Dev env.

**Comment by amolsontakke3576** [comment]
Verified with @wanyaland and now for ICLA `EventCompanyName` removed.
PFA
![Screenshot 2021-01-08 at 16.32.59.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/b72d94ef-bd3d-49a3-9adb-80e713183f26)

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576 , he verified that for CCLA, EventCompanyName is being properly returned so this is not broken.
