### ISSUE TITLE
CLA Group Validation Service

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1268]
## Summary

Define and Implement and CLA Group Validation Service

## Background

Given the CLA Group create workflow, we need an intermediate step to validate the CLA Group Name and the CLA Group Description. This task is to create an endpoint that the UI can invoke to validate the parameters.

This service will check:
- CLA Group Name is unique
- CLA Group Name is within the min/max characters for a CLA Group Name
- CLA Description is within the min/max characters for a CLA Group Description

## User Story

As a Project manager, I want to validate the CLA Group name and description as I walk through the creation wizard.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [PRD Table 1 - Step 2a](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2#ProjectConsoleforEasyCLAV2-Table1.CLASetupforaFoundation(CNCF))

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/1269

**Comment by dealako** [comment]
Pushed to DEV.

API Docs: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/validateClaGroup
Functional Tests: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/cmd/functional_tests/cla_group/cla_group.go#L167-L171

@nirupamav ready for review. I made an initial guess at the min/max requirements for CLA Group Name/Description: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.v2.yaml#L2977-L2995

Let me know and we can review/adjust these values based on UI/DocuSign experience.

**Comment by nirupamav** [comment]
@dealako 
In V1 CLA Group accepts **min 1** and **max 150** characters

**Comment by nirupamav** [comment]
**Tested and observed below issues**
1. When cla_group_name is not provided in the payload "valid": true is returned in the response. Since we have not provided the cla_group_name 400 should be returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f0e691a6-abba-4f46-9e50-79fab213f373)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6629e5ec-0b8c-40e7-8a08-46113e289805)

2. cla_group_name is accepting only spaces and "valid": true is returned in the response instead of 400
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a2dc9f52-6c74-4b98-ba36-c345ba5e6f06)

3. 422 response code is returned instead of 400 when data less than 3 characters or greater than 256 characters are provided
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8c1f0dcd-cf91-4f15-86fa-2bc3e258d719)

4. When data less than 3 characters or greater than 256 characters are provided for both cla_group_description and cla_group_name, error message contains info about only cla_group_description
In UI when user tries this scenario, user will fix only description field as error message gives info about only description. Again when trying to error is displayed for cla_group_name and user has ti again fix the cla_group_name. So I guess error message in response should include info about both fields based on the data provided
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/76e9aebc-254b-4ef1-b0fa-10506d8f4a9d)

**Comment by dealako** [comment]
Pushed PR: https://github.com/communitybridge/easycla/pull/1541

Previously added CLA Group Name validation as part of swagger specification
Added CLA Group Name validation as part of swagger specification
422 Error will be returned when the input does not match the swagger spec

**Comment by dealako** [comment]
Merged pull request.

**Comment by dealako** [comment]
Let's standardize on 
minLength: 2
maxLength: 255

**Comment by nirupamav** [comment]
@dealako 
Earlier while creating CLA Group I was able to provide special characters for CLA Group Description. However today it failed with 422. Not sure if the fix for this ticket has caused the issue.
Also could you please let me know what type if characters are allowed for both cla_group_description and cla_group_name
![image](https://user-images.githubusercontent.com/60865903/89767072-d1922200-db16-11ea-9187-98434b16eac5.png)

**Comment by dealako** [comment]
Updated - limited CLA Group Name to 100 characters due to DocuSign limit on issue #1497.  CLA Group Name must:
- starts with alphanumeric or Latin character (allows for non-asccii letters)
- second characters and beyond can be alphanumeric or Latin, plus (, ), [, ],+,-,.,/ - see: https://regex101.com/r/JHX6k8/1
- min length: 2
- max length: 100

**Comment by nirupamav** [comment]
**Verified that 
cla_group_name accepts min 2 and max 100 characters
cla_group_description accepts min 2 and max 256 characters**

**_Tested and observed below data is accepted_**
alphabets
12
_ (underscore)
+
(
)
[
]
- (hyphen)
Other languages characters 
```
Randomly tested few languages mentioned in https://www.regular-expressions.info/unicode.html. Below are the tested values
кириллица
اختبار
փորձարկում
测试
क ख
百科全書 百科全书
ᘛziᘕzazoze
ᎢᏣᎵᏍᎠᏁᏗ
ასომთავრული
δοκιμή
테스트
```

**Comment by nirupamav** [comment]
@dealako 
As per https://regex101.com/r/JHX6k8/1 below special characters needs to be accepted. However it is not accepted. Could you please confirm if they should be accepted
`. ,`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/23351254-67e6-48f6-9e50-3fd1db890047)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c450b8c2-ac8b-4804-92ff-7e44162d9c63)

**Comment by dealako** [comment]
Will add . and , to:
