### ISSUE TITLE
Change checkbox text on individual contributor screen.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#1326]

**Comment by nirupamav** [comment]
**_Verified and observed that the issue is fixed_**
**When document is generating**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/528bcf9c-17d4-4084-b159-0042da16f484)

**When document is generated**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b20e58b8-7590-4c4c-9a9b-0fc27424cf40)

**When document generation fails for e.g. when template is not generated for the CLA group**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/25fe88b7-6b2b-4d74-bb39-ecea14c97850)
