### ISSUE TITLE
Corporate Console: GitHub Org Whitelist: Connect GitHub Throws Error

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#133]
**Error Message**: AccessDeniedException: User: arn:aws:sts::716487311010:assumed-role/cla-backend-prod-us-east-1-lambdaRole/cla-backend-prod-apiv3 is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:716487311010:table/cla-session-store
	status code: **400**, request id: **MPAH2B82E2H44L5OSHTEFQB44VVV4KQNSO5AEMVJF66Q9ASUAAJG**

https://api.lfcla.com/v3/github/login?callback=https://corporate.lfcla.com/#/company/920783b1-b701-4d3b-8095-69fe65337fb2/project/2882af9c-76a9-4f92-834f-899d6ace9699/orgwhitelist

Project Impacted: **OSQUERY**
Company Impacted: **Trail of Bits**

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/64035988-bb62a000-cb17-11e9-95f1-b752df80b2c6.png)

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/64036023-d208f700-cb17-11e9-8608-76d691ec17ae.png)

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/64036096-011f6880-cb18-11e9-892f-586307dde9f3.png)

**Comment by dealako** [comment]
After an initial review, this error seems to be related to a misconfigured AWS SSM parameter value. Under the production AWS account, this value is looked up using the key: `cla-session-store-table-{STAGE}`, which in this case was: `cla-session-store-table-prod` for production. The value was set as `cla-session-store` as identified in the above ticket.  However, our DynamoDB table naming convention is: `cla-{STAGE}-...`. In this case, the table we need to access/leverage is called: `cla-prod-session-store`.

So, to resolve the issue, the `cla-session-store` value was updated to be `cla-prod-session-store`. This must have been the original value as set by the previous/original team as this was not changed recently. Since the go backend re-loads the SSM values when the lambda starts (not at package/build time), the updated value will be loaded and used the next time the lambda starts. No need for a coding change.
