### ISSUE TITLE
Establish user's connection with a company on contributor acknowledgement on both GitHub and Gerrit

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1357]
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a100a81f-0166-451a-97ec-b6e2fc56df19)
When a user acknowledges that they are in approved list, EasyCLA API needs to call a user service or organization service api to associate this user with this company.
Need to figure out how this can be done in Gerrit also.

**Comment by nirupamav** [comment]
**_Tested for github and observed below issues. Since user with LFID flow is not working have not tested the user without LFID_**

**1. Corporate Contributor who has LFID and is acknowledged for CLA group and  also signs ICLA is not assigned with any role to be associated with the organization**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6aa695e6-b800-4d51-b408-b7412ec4538a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f785d9b2-e746-4f9c-bf7c-76cf1fbdb9fc)

**2. Corporate Contributor who has LFID and is acknowledged for CLA group and need not sign ICLA is not assigned with any role to be associated with the organization**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d5891f46-af03-4b69-8c1e-2976303d94f0)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dbfc7bd5-5310-44f6-8baf-5d8bd0d6e346)


**_Contributor Info_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2f695ad9-4ade-493f-99ee-301515b54377)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/55b97ea0-fddf-49a7-a972-0d6bfa78839e)

**Comment by amolsontakke3576** [comment]
@wanyaland @rinkeshbhutwala can you make this endpoint without an Authorization header? For this flow, we don't have a login screen,

**Comment by nirupamav** [comment]
@wanyaland @amolsontakke3576 
What is the fix for this ticket. What am I supposed to test in this ticket

**Comment by wanyaland** [comment]
@nirupamv test whether user has been given contributor role associated with the organization

**Comment by nirupamav** [comment]
Verified in #1478
