### ISSUE TITLE
Forwarding flow when user doesn't have a LFID

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1417]
To be implemented at step 3.1 of Table 3 and step 4.1 of Table 4 in the following PRD.
https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2 

When the user clicks "Proceed" the user is taken to "CLA Manager Designee Assigned" entry point on Corporate Console
**If the user doesn't have a LFID**. 
- [ ] When the user clicks proceed they will be taken to LFID creation screen. User can create LFID 
- [ ] Since we have the organization information, in the backend we can do the organization association with that LFID. This will not work if the user clears their browser cache
- [ ] After organization association is completed, user will be redirected back to CLA corporate console where they can proceed with CLA signing
- [ ] Dialog box needs to be updated to tell the user following extra message "We detected that you don't have a LF Login. You will be directed to Linux Foundation sign-on screen to create LF Login and subsequently you will be able to sign CLA"

**Comment by nirupamav** [comment]
Since the Create Organization flow is changed, will test this ticket once the changes are implemented
So far logged bugs #1499, #1509

**Comment by nirupamav** [comment]
Observed that below message is displayed and user is redirected to github instead of corporate console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e751f908-aa97-4ce6-8d6b-c70efeb7a368)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c6dc7f72-907a-40f6-8f5f-4868a817f66f)

**Comment by pranab-bajpai** [comment]
Add a message to the dialog box before your redirect the user. 
Note: To continue please disable pop-up blocker for this site.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/813782b2-7d82-4526-8e15-475c36bc6cf0)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8b77710d-5208-4026-bf8e-168aac129807)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/46c51418-9211-49a8-a01f-920106f4af43)
