### ISSUE TITLE
Project Console Gerrit API

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1451]
## Summary

Write following api 
1) Add Gerrit
2) Delete Gerrit
3) List Gerrit

## User Story

- As a project manager, I want to manage gerrits for cla-group

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**

**_Add Gerrit_**
**1. 422 is returned empty object is provided in the payload or when mandatory fields are not provided in the payload while adding gerrit**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/34ecda51-c662-4410-acfb-ab82f07b52f3)

**2. Appropriate error message is not displayed when string value is provided for groupIdCcla or groupIdIcla is provided in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/51e44b9a-d5dc-4c85-a37c-144a9027f370)

**3. Able to Add gerrit instance with gerritName and gerritURL having only spaces**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6a226398-099b-4079-ad40-ce78995a689f)

**4. gerritUrl accepts free text and there is no validation for url format**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/580278ec-54bc-4566-aa83-aa9d4e93088a)

**5. Value of groupIdCcla is returned for groupIdIcla in the response**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d54dbf72-bd78-4d9b-8a8b-90ca07130ad9)

**6. Able to add duplicate gerrit instance**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2f473c8f-d986-4fed-a7a1-8845bb0f7981)

**7. Appropriate error message is not displayed when invalid groupIdCcla or groupIdIcla is provided in the payload**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3cfe7cfd-3dad-4447-98db-b581478b8972) 

**8. Able to add gerrit instance with only groupIdIcla or groupIdCcla when CLA group is enabled for both**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3b0cd38e-c167-42bc-8f36-105a528b14d5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ac2ced24-b89a-4d7d-bff3-5fec12af3dfa)

**9. groupIdIcla is not returned in the response when trying to add gerrit instance with only groupIdIcla**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/85e9d012-4c73-44c4-994c-4cdf637508ad)

**10. version is V1 while adding gerrit**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b8db6fb0-846b-4f47-80cc-cac25cebb46f)

**------------------------------------------------------------------------------------------------------------------**
**_Get Gerrit_**
**1. Value of groupIdCcla is returned for groupIdIcla in the response**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/84c54163-b4a9-4842-8a26-1a92615ada29)

**2. 200 with empty list is returned instead of 400 when cla-group and projectsfid provided in the url are not associated with each other or when invalid cla-group/projectsfid is provided in the url**

**3. groupIdIcla is not returned in the response when gerrit instance with only groupIdIcla exists**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b33c816d-aa9a-4ed8-af19-34b48dd442f7)

**Comment by nirupamav** [comment]
**Tested and observed below issues. Except below issues all other issues mentioned above are fixed**

**_Add Gerrit_**
**6. Able to add duplicate gerrit instance**
**8. Able to add gerrit instance with only groupIdIcla or groupIdCcla when CLA group is enabled for both**

**Get Gerrit_**
**4. Able to add gerrit instance with url http://geerit, However while fetching the gerrit instance with Get action observed below issue**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3ed8cdf4-71f7-4d91-bda2-609b5e53d138)

**Comment by dealako** [comment]
@rinkeshbhutwala to summarize the Gerrit validation:

Project Manager Provides this as input:

![image2020-8-13_22-50-36](https://user-images.githubusercontent.com/519609/90570745-37108f00-e165-11ea-9c29-1ad2e8b77b8c.png)

[Via API](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.v2.yaml#L2223)

- Gerrit Name: Can be any string value based on the Swagger regex rules.  Reject if we identify a duplicate Gerrit name in the database - don't allow.
- Gerrit URL: we only allow Gerrit Instances from a known list. I have submitted a PR with [this Swagger Doc update](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/common/add-gerrit-input.yaml#L15) - [see swagger doc](https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addGerrit).  Please add validation logic to check the values and reject if the value does not match from our list.
- Group ICLA - currently the values are numeric, but we don't restrict - string is OK - the numeric-only value may change in the future.  Ensure value differs from submitted Group CCLA and that we do not have a duplicate value in the database for ICLA or CCLA group ID - should be unique across both column values in the database. If there is a duplicate, then I'm 100% sure this is a mistake by the Project Manager. This value is obtained from IT and should be just plugged in.  We can't validate further.
- Group CCLA - currently the values are numeric, but we don't restrict - string is OK.  Ensure value differs from submitted Group ICLA and that we do not have a duplicate value in the database for ICLA or CCLA group ID - should be unique across both column values in the database.  This value is obtained from IT and should be just plugged in.  We can't validate further.

@nirupamav please provide comments/feedback if you know otherwise.

**Comment by dealako** [comment]
https://github.com/communitybridge/easycla/pull/1615

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. Appropriate error message is not displayed when 12 characters are provided for both groupIdCcla and groupIdIcla**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ddd94181-b768-4349-90b8-872b0f9fda75)

**2. Able to add duplicate gerrit instances for same project with same gerritName, groupId and gerritUrl**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1fe708be-7acc-40b6-be8d-e53dfc536e04)

**3. Able to gerrit instance with same gerritName, groupId and gerritUrl for different projects that are associated to same CLA Group**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/52dafb0b-d69f-4b23-a2f8-48117fc1fa60)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fc114618-9b32-4174-844d-2eeae7e668a2)


**4.Able to add gerrit instance with only groupIdIcla or groupIdCcla when CLA group is enabled for both**

**Comment by nirupamav** [comment]
**Issue4 is still reproducible. Able to add gerrit instance with only groupIdIcla or groupIdCcla when CLA group is enabled for both**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b12845f-0469-4b44-937a-56b44cd70a8f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cf90e2d6-0591-4248-a7b0-477d8a601812)

**Comment by rinkeshbhutwala** [comment]
@nirupamav Can you please check the above screenshot which @dealako is posted in that mention that only one id is required to create a Gerrit instance for that can you please confirm with @dealako issue no. 4?

**Comment by nirupamav** [comment]
Verified below scenarios. Testing is still In progress
1. Duplicate gerrit instance with same ICLA or CCLA groupId cannot be created
2. If CLA Group is enabled for both ICLA and CCLA, validation is implemented to check if both ICLA and CCLA group Id is provided

**Comment by nirupamav** [comment]
Verified that It is working as expected
