### ISSUE TITLE
V2 - Company Not Found - Organizations are not auto suggested when entered org name matches multiple organizations

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1613]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter value Samsung in Enter Organization Name field
11. Observed that empty data is returned by API call and there is no auto suggestion with of the companies in the UI. When checked in Org service there are many companies matching Samsung
https://api-gw.dev.platform.linuxfoundation.org/organization-service/v1/orgs/search?name=samsung

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5198b3e2-2bda-4b31-9971-571ad6361af1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f5b47448-206d-4d4e-bbf9-cccaef81b9f8)

**Comment by dealako** [comment]
Add Organization Search to this modal:

- When user types the URL or the Name - perform look-ahead search. If any matches, show the user. If the user clicks on the results, pre-fill the form with the information.

In the previous screen, the user may type and not find their Organization - perhaps due to a typo or other reason. Now they come to this view and enter in the value. If there is a match, perhaps because they have spelled it correctly, we should show the potential matches and give them an option to select/prefill. If they select an existing value, then we should follow the workflow based on the existing Organization (not new Organization).

**Comment by nirupamav** [comment]
Observed that organizations are suggested by org name or website. When clicked on the auto suggested orgname, details are auto populated and inline alert message is displayed. User is able to navigate to No Signed CLA Found dialog when clicked on Next button and proceed with CLA Manager Designee flow
Observed that for few website data is not auto populated for few scenarios and issue is tracked in #1684

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/92a21f2d-2804-4b0c-86a1-ac3f180e4ca7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a549cc79-538a-4f29-822e-64186a7ede78)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/83b87595-9a02-4944-83ea-a0019d9cdbe7)
