### ISSUE TITLE
Gerrit Contributor email does not populate in form to send to CLA Manager (Approved List request)

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1670]
## Summary

When a contributor is not in a company's approved list for a CLA, a Gerrit contributor will sometimes be unable to submit the form to send to their manager because their email(s) do not populate.

## Background
1. Log into Gerrit with a user who only has a "lf_email" in the user table and no "user_emails" listing
1. Attempt to verify with a CCLA by going to settings->Agreements->New Agreement-> CCLA->redirected to EasyCLA
1. Log into EasyCLA with same Linux Foundation account as Gerrit and select "Amdocs" from the list.
1. Observe you are not on the Approved List, select "contact" cla manger
1. Observe your email does not populate and you are unable to send the form.
1. Add a "user_emails" entry for your user in the user table and add one or more email addresses.
1. Observe form now populates an email and you can send it (don't).
1. Observe that sometimes the "user_emails" section is populated for the user in the api call even when the user has no user_emails listed in the database and the form is filled and able to submit.

Call:
https://api.lfcla.com/v2/user/1a75f09e-c97e-4392-b438-c9ac606f20b6
Response:
{"date_created": "2019-08-21T10:44:07.595969+0000", "date_modified": "2019-08-21T10:44:07.595980+0000", "lf_email": "hwillson@contractor.linuxfoundation.org", "lf_sub": null, "lf_username": "HWillson", "note": null, "user_company_id": "4b8227b3-990b-4897-8d39-0d4323b50769", "**user_emails": ["hwillson@contractor.linuxfoundation.org"],** "user_external_id": null, "user_github_id": "46732999", "user_github_username": "WillsonHG", "user_id": "1a75f09e-c97e-4392-b438-c9ac606f20b6", "user_ldap_id": null, "user_name": "Heather Willson", "version": "v1"}

DB listing:

{
  "date_created": "2019-08-21T10:44:07.595969+0000",
  "date_modified": "2019-08-21T10:44:07.595980+0000",
  "lf_email": "hwillson@contractor.linuxfoundation.org",
  "lf_username": "HWillson",
  "user_company_id": "4b8227b3-990b-4897-8d39-0d4323b50769",
  "user_github_id": 46732999,
  "user_github_username": "WillsonHG",
  "user_id": "1a75f09e-c97e-4392-b438-c9ac606f20b6",
  "user_name": "Heather Willson",
  "version": "v1"
}

1. Review this behavior so that it populates in all cases. It probably isn't populating the first time the user entry is created in the database from Gerrit information.

**Comment by dealako** [comment]
@rinkeshbhutwala - ask @nirupamav for help verifying/validating this. This issue was reported by @WillsonHG in PROD.

This might be a super complicated workflow that may require some help diagnosing.  Essentially, when a user first comes to the Corporate Console either as a GitHub User or a Gerrit User, we want to create a User Record in our database (cla-{stage}-users table).  For Gerrit users, they will be already authenticated since Gerrit requires LF authentication to do anything.  So, the workflow inbound should at some point create the user record with their email.  Later, I think, we use their user record email address to send for help if they are not on the Approval List or whatever.

Generally:

We have an inbound like from Gerrit which looks like:

LF Gerrit Link:
https://gerrit.linuxfoundation.org/infra/settings/new-agreement

Agreements Link from within Gerrit (examples):
X https://api.staging.lfcla.com/v2/gerrit/4405798d-913c-4a8d-a906-dd61d91c2d62/individual/agreementUrl.html
OK : https://api.dev.lfcla.com/v2/gerrit/4405798d-913c-4a8d-a906-dd61d91c2d62/individual/agreementUrl.html
OK : https://api.dev.lfcla.com/v2/gerrit/4405798d-913c-4a8d-a906-dd61d91c2d62/corporate/agreementUrl.html

Which should hit our API, which then: 1) loads the project record (CLA Group) and creates on-demain and loads the user record, and returns a super small HTML page to the user asking the user to proceed.  Basically, we generate a new redirect link which includes the project id (CLA Group ID) and the user id in the URL so that the Contributor console has all the information it needs... This is python code, but you should be able to understand and read it (ask @wanyaland for help, if needed).

We need to confirm this and verify that the user record saves the email address as described above.  The user's table is a bit weird as it has two columns for email: `lf_email` (string, primary email) and `emails` (which is a list of strings - alternative emails).

I am wondering if this is a timing issue or perhaps we don't save the email properly (python, ask Harold for help if needed) .... or later in the v1 Contribtor Console load the user record with the emails properly (seek Amol's help here if needed).

Heather is EDT time zone - so, please reach out directly with her if you need help before I'm online.

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland For contributor console V1 in Gerrit flow We have used below endpoint and I guess its payload is changed now and because of this I and @rinkeshbhutwala not able to test this. 

Request URL: https://api.dev.lfcla.com/v2/check-prepare-employee-signature
Request Method: POST
Status Code: 400 

{"errors": {"project_id": "Required parameter 'project_id' not supplied"}}

@wanyaland Do I need to change payload for V1 also?

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland Gerrit links provided above are not working it gives an error 
{'errors': {'gerrit_id': 'Gerrit Instance not found'}}

and because of this I and @rinkeshbhutwala not able to test this ticket. can someone fix it soon so we can move ahead?

**Comment by WillsonHG** [comment]
@amolsontakke3576  I was able to recreate this is dev with my user that did not have any "user_emails". Most Gerrit users will only have lf_email. Before you start, make sure your dev user has no "user_emails".

For the dev environment:
1. gerrit.linuxfoundation.org -->Settings --> Agreements -->New Agreement-->Test Project 2 CLA --> Please review the agreement link
1. Change the url to remove the word "individual" and replace with "corporate" and reload.
1. Screen will now say "Proceed to Corporate Authorization"
1. Select "Biarca" from company list. This is the only company in Dev which has a CLA signed for the project.
1. Observe you are not in the Approved List, select "Contact" manager
1. Observe that SOMETIMES the email does not populate in the "Your Email to Authorize" section. The error shows 
![image](https://user-images.githubusercontent.com/46732999/91616163-2fb26800-e953-11ea-851c-e0adcc33065f.png)

The method on line 104 at https://github.com/communitybridge/easycla/blob/master/cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts looks to be the culprit.

If I hit cancel or X on the modal and try again, it might retrieve the email and it might not. It appears to be random or intermittent.

If instead of choosing Biarca and choosing instead a company that does NOT have a CLA signed for the project (any other company), the modal is different and I cannot reproduce the issue.

**Comment by amolsontakke3576** [comment]
@WillsonHG I have tried your step but `Test Project 2 CLA` is disabled and error shown at the bottom `Agreement already submitted.` Do you have any other option to make it works?

**Comment by dealako** [comment]
@WillsonHG can you follow up/sync with @amolsontakke3576 and @rinkeshbhutwala on this issue?  Where are we at on this topic?

**Comment by WillsonHG** [comment]
@amolsontakke3576  Were you able to test this scenario with the user credentials I gave you on dev?

**Comment by dealako** [comment]
@amolsontakke3576 add some defensive code around the code fragment that @WillsonHG has identified https://github.com/communitybridge/easycla/blob/master/cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts#L106-L115.

Make sure that the email is present - if not - determine why... is the login session info not correct, expired, or deleted for some reason. Based on the error message, the user object is valid, but the `user.emails` is null.

**Comment by amolsontakke3576** [comment]
@dealako As per your above comment `Based on the error message, the user object is valid, but the user.emails is null.` below is the explanation

If you come to contributor console from Github then we have `user.emails` as well as `lf_email` (depends on the user logged in to the LF or not) in the user object. 

But for Gerrit case, LF login is compulsory for a contributor so we have only `lf_email` and `user.emails` is always null.

As per code written in the frontend, I made it smarter and it never throws a null console error for both Gerrit and Github flow.

**Comment by dealako** [comment]
If possible, as you recommended, we can implement smart logic to store user info in local storage. Only go to the user service to fetch user information if it is missing from the local storage (like a cache).

**Comment by dealako** [comment]
@amolsontakke3576 status update?

**Comment by gatopeich** [comment]
I found there is a workaround for this which actually makes things worse!
Ticket is here https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-4350
Then I found this issue searching for the offending code.
This code:
```
            if (this.userEmails.length === 1) {
                this.form.controls['user_email'].setValue(user.user_emails[0]);

```
Should be like this:
```
            if (this.userEmails.length === 1) {
                this.form.controls['user_email'].setValue(this.userEmails[0]);
```
Otherwise there is an exception and the contact form is not displayed at all.

**Comment by amolsontakke3576** [comment]
> I found there is a workaround for this which actually makes things worse!
> Ticket is here https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-4350
> Then I found this issue searching for the offending code.
> This code:
> 
> ```
>             if (this.userEmails.length === 1) {
>                 this.form.controls['user_email'].setValue(user.user_emails[0]);
> ```
> 
> Should be like this:
> 
> ```
>             if (this.userEmails.length === 1) {
>                 this.form.controls['user_email'].setValue(this.userEmails[0]);
> ```
> 
> Otherwise there is an exception and the contact form is not displayed at all.

I don't think so 
we have already taken care of this 

` this.userEmails = user.user_emails || [];`

**Comment by gatopeich** [comment]
> ` this.userEmails = user.user_emails || [];`
I saw the issue debugging the deployed javascript and this line was not present at the spot.

At any rate, there is a robustness issue in checking length of one array `this.userEmails` to access a different one `user.user_emails`.
