### ISSUE TITLE
CLA Bot exhibiting non deterministic behaviour

### ISSUE THREAD

**Issue by justinsb** [communitybridge/easycla#1675]
I have two PRs, and they have the same set of commit authors.  Yet one of them has clabot=yes, and one has clabot=no.

The two PRs are https://github.com/kubernetes-sigs/etcdadm/pull/170 and https://github.com/kubernetes-sigs/etcdadm/pull/162

I compared the authors using:
`diff <(git log justinsb/add_etcd_manager_4 | grep Author | sort | uniq) <(git log justinsb/add_etcd_manager | grep Author | sort | uniq)`

or equivalently: `diff <(git log 8ec0490d748bcadb8900b6235c0f230a2c9b3109 | grep Author | sort | uniq) <(git log 2c7d16cbe9d50ebc90792d5d9e79f73e4aa21e6c | grep Author | sort | uniq)`

No differences were shown.

**Comment by WillsonHG** [comment]
Hello @justinsb  Those 2 PRs are using the CLA v1 bot that isn't managed by the EasyCLA system. All Kubernetes repos are still on the CLA v1 system right now.

In your case, the https://github.com/kubernetes-sigs/etcdadm/pull/162 has over 700 commits. Each commit must be authored by a user attached to their GitHub account so that we may verify their identity and that they have signed a CLA. Some of those commits are showing the grey octocat icon because they are incorrectly authored and not tied to a user. The link in the "details" of the CLA check shows more information about how to fix those commits. https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user Quickly glancing through the commits, I see that several from "Daniel Lipovetsky" in 2019 aren't linked.

If you need further assistance with the CLA checks, please open a support ticket at support.linuxfoundation.org Thank you!
