### ISSUE TITLE
V2 - Project Console - Not able to delete github repositories or github organizations

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1682]
**_Observed 400 is returned when trying to delete github repositories or github organizations. Observed same issue from UI as well_**

**Deletion of github repository**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/980f97d6-5617-49c4-933c-92539c9ba726)

**Deletion of github organization**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/50ffcbf2-9064-4f03-a9c7-76f30f5d6186)

**UI**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6706ce67-8de8-4de5-a96f-ceee9423ab49)

**Comment by dealako** [comment]
@nirupamav this regression was a result of changing the repository delete logic to be an update call - where we instead of deleting the repo we actually just disable it.

Created PR: https://github.com/communitybridge/easycla/pull/1688

- Resolved DB update syntax error
- Refactored repositories table API and DB logic - renamed service and DB functions, added enabled/disabled options. Changed deleted to disabled. General API cleanup.

If possible, can you perform a thorough review of the repository add/delete logic from both v1 and v2? I have updated many files to clean up the API and the database logic.

**Comment by dealako** [comment]
Merged PR.  Pushing to DEV.

**Comment by nirupamav** [comment]
**Verified that able to delete Github repo and github org. Will perform regression and log new tickets for any regression issues. Closing this ticket as the actual issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e47e6245-4374-4e4c-ba44-ccee9e783293)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ba73226c-cc74-444a-abe0-b29ef16d2194)
