### ISSUE TITLE
V2 - CLA Not Signed - Project/Foundation Level CLA Group - User is stuck at Accept Invite page after creating LFID by accessing Accept Link from Email notification

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1753]
**Prerequisite**
1. Create a CLA group with CCLA enabled 
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and select company that has not signed CLA for the project and already has company owner
**_NOTE: Observed same issue for company without company owner as well_**
9. Click Proceed
10. Click No
11. Enter email of user who does not have LFID
12. Click Submit
13. In the Email notification click Accept Link
14. Create account
15. Verify email
16. Observed that user is redirected to accept-invite page and no action is performed when clicked on Accept The Invitation button. However cla manager designee role is assigned for the user
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a990423a-835c-4934-8fae-f683907e132c)

**Comment by rinkeshbhutwala** [comment]
@dealako I have a discussion on this ticket with Prabodh and Yogesh and they suggested to not to use this link **https://lfx.dev.platform.linuxfoundation.org/accept-invite?inviteid=319e3de5-7134-4c60-a97f-c4e8055d1991** instead of this we need to use only this one **https://lfx.dev.platform.linuxfoundation.org/** on front-end side so the user is redirected to the signup page and everything is working fine after that so this is not a part of the cla-service endpoint.

This is the ticket that Yogesh is working on to fix the issue.
**https://jira.linuxfoundation.org/browse/IAM-1069**

**Comment by dealako** [comment]
I think the generated user-accept link by Yogesh will take the format of: 

{code}
<a href="USERACCEPTLINK">Accept Invite</a>
{code}

So this link needs to be updated by the platform team to resolve this issue.

**Comment by sudhakar-proxima** [comment]
@dealako You are right. The Core services team has updated the link to point to LFX Landing page, instead of acceptInvite page.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
