### ISSUE TITLE
V2 - Company Not Found - Request Failed error displayed due to CORS issue after creating company and creating account from SSO to assign CLA Manager designee role

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1774]
**Prerequisite**
1. Create a CLA group with CCLA enabled (I tried the flow where CLA Group is for standalone project which does not have any parent or any child projects)
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8.Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter new company details
11. Click Next
12. Click Proceed
13. Click Yes
14. Click Proceed
15. User is redirected to SSO. Create SSO account and verify email
16. User is redirected to contributor console and Request Failed message is displayed due to CORS error
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eec3aeae-b844-4ea3-98d6-a111aa3626e2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/757eafe3-0c18-4efc-b97b-5a73fdc129cc)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eb3875cb-29ea-46fd-a36b-579749c7e96a)

**Comment by wanyaland** [comment]
The CORs issue is caused due to a delay on the core services endpoints invoked ie (assigning company-owner role & assigning cla-manager-designees). So in summary the endpoint took 1.20 secs to do both role assignments. 
I broke down the cla-manager-designee endpoint into 2 endpoints -> One for assigning cla-maanger designee which took 50s and one for company-owner role which took 40s. This separation can resolve the issues caused by the lambda timeout

**Comment by wanyaland** [comment]
> @wanyaland I have merged your PR: #1784

Thanks

**Comment by nirupamav** [comment]
Verified that the issue is fixed
