### ISSUE TITLE
V2 - Contributor console - Multiple user records are created in users table each time contributor logins with a different user with LFID

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1810]
Observed that in below flows of contributor console, if contributor logins with different user, multiple user records are created

1. Select existing Company -> Select Yes in Not Signed CLA -> Create user -> redirected to corporate console
2. Select existing Company -> Select Yes in Not Signed CLA -> Login as existing user -> redirected to corporate console
3. Create company -> Select Yes in Not Signed CLA -> Create user -> redirected to corporate console
4. Create company -> Select Yes in Not Signed CLA -> Login as existing user -> redirected to corporate console

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/57743f7e-aae0-4555-9b66-2b35f842ddb2)

**Comment by dealako** [comment]
@makkalot this is potentially a python problem with the flow:

1. GitHub user is Gated by EasyCLA
1. GitHub user clicks on EasyCLA link to get authorized
1. First time, GitHub user is presented with Authorization/Confirmation
1. GitHub user is taken to EasyCLA v2 API
    1. Logic looks into EasyCLA users table. Creates if not exist.
    1. Logic loads the user record
    1. Logic looks up the CLA Group record (cla-projects table entry) (based on provided GH repo ID)
1. etc. etc.

Please review the Flow logic where the GitHub user record is auto-created/loaded. We should not create duplicate entries.

**Comment by dealako** [comment]
Also, potentially review this flow/logic where we setup a Docusign flow (lots of user lookup logic):

https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/docusign_models.py#L356

**Comment by dealako** [comment]
The UI processes this request differently and as a result, this issue is no longer a problem. Please verify.

**Comment by wanyaland** [comment]
Noticed that duplicate records were not created.. However the new LF login created in the flow was not getting updated for user. User maintains old record with previous lf Login

**Comment by dealako** [comment]
For the use-case where the same user accomplishes:

- GH user navigates to EasyCLA with GH user ID. Directed to log in. User logs in as LFUser1.
- GH user navigates to EasyCLA with GH user ID. Directed to log in. User logs in as LFUser2.

In this scenario, we do not properly track the GH user id and the LF ID associations.

This is a seemingly obscure use-case generated by our clever test team.  I recommend we do not add additional logic at this time to resolve this.  At some point, we will transition to use the [myprofile](https://myprofile.dev.platform.linuxfoundation.org/) console where we can ask the user to associate their GH user ID, LF user id, and other social media affiliations. This will allow the user to manage it from that console (rather than us having a separate table/mapping).

**Comment by vinod-kadam** [comment]
Moved it to backlog.

**Comment by vinod-kadam** [comment]
@dealako  & @pranab-bajpai,  I marked it as Post-EasyCLAv2Release so that we can track it after the 1st easycla release & have moved it from "Ready for QA" to "Backlog" as some work would be needed in the future for this one.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
