### ISSUE TITLE
Project Console - New CCLA Template Not Added to Document List

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1873]
## Summary

Project Console - New CCLA Template Not Added to Document List

## Background

When a new template is generated after an existing set of CLA templates are present, only the ICLA document details are added to the document list. The CCLA appears to only update the date/time of the new PDF.  Expected behavior is that a new document is added to the list of documents.

## Expected behavior

A new document is added to the list of ICLA/CCLA documents.

## Screenshots

Template was re-generated several times - CCLA only shows one document:

![Screen Shot 2020-09-25 at 12.07.56 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/9bfddc54-0a54-454f-b6b1-5920ff151f8a)

ICLA shows four:

![Screen Shot 2020-09-25 at 12.08.09 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/13b54045-91be-4141-8a9e-bd4761922705)

## Environment

Please complete the following information:

* Environment: DEV, STAGING and PROD 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Updated code to resolve the issue. CCLA's were not being appended to the list.  Created PR: https://github.com/communitybridge/easycla/compare/master...dealako:bug/1873-ccla-template-not-added-to-doc-list?expand=1

Ready for confirmation validation.

How to test:

1. Create a new CLA Group with both CCLA and ICLA, note the Project Name, Entity Name, and email address
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there is one PDF for ICLA.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there is one PDF for CCLA.
1. Find CLA Group in the EasyCLA database - cla-dev-projects
1. Observe that there is one element in the project_individual_documents field and one element is in the project_corporate_documents field.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe icla and ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format
1. Identify the CLA Group again in the Project console
1. Press the Select Template button, Select Apache Style Template
1. Enter new values, note values you entered, use different values from the previous attempts
1. Generate new templates
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for ICLA. Ensure most recent PDF is first and selected.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for CCLA.  Ensure most recent PDF is first and selected.
1. Find CLA Group in the EasyCLA database - cla-dev-projects - may require a new search to "see" updated values.
1. Observe that there are two elements in the project_individual_documents field and two elements are in the project_corporate_documents field.  The first element is the first one added, the second element is the most recent/latest one added.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe that two icla and two ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format

**Comment by nirupamav** [comment]
**Verified that the issue is fixed. However there is issue at step3 which is tracked in #1871**

**_Tested for New CLA Group/Existing CLA Group. Also tested for Only CCLA, Only ICLA, Both CCLA and ICLA. However observed issue at step3_**

1. Generated templates and observed that files are generated in below format which is as expected
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c3ce5332-9d45-487a-9f2a-c3a57aa40a1e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6f2d4d36-9fae-4105-8986-a861bfdc08ae)

2. Generate templates again. Observed that 2 elements exists for project_individual_documents and project_corporate_documents fields
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d6a5c02e-1df1-4863-8f38-7a7a740890db)

**_3. Observed that recent pdf is selected. However when clicked in PDF icon to view the modal popup, first time generated pdf is selected. If the modal popup is opened again then recently generated pdf is selected. Each time when modal popup is opened, alternatively recently generated and first time generated pdf's are selected. Observed same issue with ICLA pdf as well. If we refresh the page or revisit the page, recently generated file is selected_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4f2d630-ecca-443b-a0fb-a0ba6104d9b9)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a4d53638-5f5d-4ef2-a031-707cae346e21)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5d3f8081-7f48-46cd-bcc6-9b2fe165b992)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/adb55e0f-c5e5-4cfc-94b9-41a072889b90)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/82bfebf3-947b-4899-a04a-8b38c37208fc)

4. Observed that while signing CCLA from Corporate Console, recently generated template is used
5. Observed that while Individual Contributor is signing ICLA from Contributor Console, recently generated template is used
6. Observed that while Corporate Contributor is signing ICLA from Contributor Console, recently generated template is used
7. Observed that in S3, templates are stored in format ccla-YYYY-MM-DDTHH-MM-SSZ.pdf or icla-YYYY-MM-DDTHH-MM-SSZ.pdf 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d4706c25-0ee7-4522-b5d6-e2a9add706a0)
