### ISSUE TITLE
Disallow System Admin Permissions for CLA Manager Activities

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1946]
## Summary

Disallow System Admin Permissions for CLA Manager Activities

## Background

As a legal requirement from the stakeholders, only CLA Managers should be able to perform CLA Manager activities.  Do not allow admins or super admins to perform these actions.

## Tasks

- [ ] In the EasyCLA permission helper utility functions, we nee allow admins to perform actions. We need separate permission checks for CLA Manager activities that do not allow admins.

For example, the following routine would allow users with admin permissions to perform the action.

```
// IsUserAuthorizedForProjectOrganizationTree helper function for determining if the user is authorized for this project organization scope and nested projects/orgs
func IsUserAuthorizedForProjectOrganizationTree(user *auth.User, projectSFID, companySFID string) bool {
	if !user.Admin {
		if !user.Allowed || !user.IsUserAuthorized(auth.ProjectOrganization, projectSFID+"|"+companySFID, true) {
			return false
		}
	}
	return true
}
```

Instead, for CLA Manager actions/endpoints/handlers, we should have a routine that does the following permissions checks:

```
// IsUserAuthorizedForProjectOrganizationTreeNoAdmin helper function for determining if the user is authorized for this project organization scope and nested projects/orgs
func IsUserAuthorizedForProjectOrganizationTreeNoAdmin(user *auth.User, projectSFID, companySFID string) bool {
	if !user.Allowed || !user.IsUserAuthorized(auth.ProjectOrganization, projectSFID+"|"+companySFID, true) {
		return false
	}
	return true
}
```

## Expected behavior

On CLA Managers, not anyone else, not admins, should perform certain actions.

## Screenshots

N/A

## Environment

* Environment: DEV 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Removed `user.Allowed` checks from ALL EasyCLA APIs.

See: https://github.com/communitybridge/easycla/pull/1959

**Comment by nirupamav** [comment]
**Tested and observed that system-admin is not able to  perform CLA Manager activities when system-admin is CLA Manager for the project. Since system-admin is CLA Manager for the project, system-admin should be able to perform CLA activities**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0ec03e81-96c4-4ff2-95ef-2590b5e03de8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a4791229-43e0-4863-bc60-391ba5f44c0b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d1820926-02fb-44ba-9c09-38e6bd994f06)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d9984ff5-ce9d-482d-a9cf-20c7db55a4cb)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dc76f0d3-455c-485a-8ffb-ad31fee44981)

**Verified that system-admin is not able to perform CLA Manager activities when system-admin is not CLA Manager for the project**
**Add CLA Manager**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cc9816bb-cc8a-4ffe-90e8-333baca41f53)

**Delete CLA Manager**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8b48210d-052e-47f1-885b-3c8aa6b4264f)

**Update Approval List**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9decffda-25fb-4365-9dae-657b4e83b85c)

**Comment by nirupamav** [comment]
As discussed in standup call, even if system-admin is cla manager, system-admin will be blocked from performing any CLA Manager activities
Moving the ticket to QA Done
