### ISSUE TITLE
Wrong email sent when user is approved access to company

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2001]
## Summary

When a user is approved access to a company, an email stating "You have now been approved as a contributor from" is sent, confusing the user.

## Background

1. go to corporate.lfcla.com
1. request to join a company
1. existing cla manager approves your access, receive an email letting you know.

## Expected behavior

The expected email should be - 

Subject: EasyCLA: Company Manager Access Approved for {company_name}
Body: 
Hello {{name}},

This is a notification email from EasyCLA regarding the company {company_name}}.

You have now been approved as a Company Manager for {company name}.  This means that you can now view and apply for CLA Manager status on projects associated with your company.

To get started, please log into the EasyCLA Corporate Console at https://corporate.lfcla.com, and select your company. From there you will be able to view the list of projects which have EasyCLA configured and apply
for CLA Manager status.

If you need help or have questions about EasyCLA, you can read the documentation at [URL] or reach out to us at [EMAIL].

Thanks,
EasyCLA support team

As found in https://docs.google.com/document/d/1jFlSq1tx66LbBwGbSfJm3QS4st68GblfzBEMZRya9gk/edit#

Current wrong email Screenshot: 

![image](https://user-images.githubusercontent.com/46732999/96281995-19ff0d80-0fa8-11eb-8bcb-4ab8d7607c25.png)

**Comment by dealako** [comment]
@makkalot can you work on this tomorrow - a higher priority item.  Above is a link to a document listing our system emails. Apparently, the above email was sent instead of the correct email. Can you review the above and if necessary coordinate with Heather on:

- [ ] Identify where the email was sent (not sure if this is golang or python code, maybe golang) - confirm details 
- [ ] Replace the email subject/body with the appropriate email content (use existing functions as needed)
