### ISSUE TITLE
V2 - Project Console - Issues with auto enable repos

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2005]
1. Create CLA Group for a project
2. Configure github org
3. Auto Enable New Repositories for the github org
4. Observed below issues

**_Issue1 - When no repositories are enabled, if we Auto Enable New Repositories, Existing repos are not enabled for CLA_**
**_Issue2 - if we Auto Enable New Repositories, New repos are not enabled for CLA_**

**Comment by dealako** [comment]
Denis:

- [ ] Please confirm we can set/reset this value through the /v4 API - confirm by reviewing the GH Org table `autoEnabled` attribute.
- [ ] Create a test organization
- [ ] Add organization to a new or existing CLA Group
- [ ] Enable Auto Enable for this Organization
- [ ] Add a new test repo to the Organization
- [ ] Observe that the callback is sent to the Python API
- [ ] Review and report on any existing logic for the callback event. Discuss with team.
- [ ] Logic should (somehow) identify which CLA group is associated with the Organization/Repo....and automatically add the repo to the CLA Group (update both repos table with the new repo)...(is this the only table we need to update??).
- [ ] Need to send an email to the PMs for this CLA Group notifying them that we have added a new repo to the CLA Group since auto enabled was selected. In the email state the 1) CLA Group 2) GitHub Organization 3) and the repo name that was added.

**Comment by nirupamav** [comment]
@makkalot 
I can think of below scenarios as of now

1. Add github and select All repositories option while installing CLA App. Enable the Auto Enable new repositories option for the github org. Add new repo to the githuborg. In EasyCLA UI, the new repo should be added and cla enabled automatically
2. Add github and select All repositories option while installing CLA App. Enable the Auto Enable new repositories option for the github org. Delete a repo which was already CLA enabled and add the same repo again.  In EasyCLA UI, the new repo should be added and cla enabled automatically
3. Add github and select All repositories option while installing CLA App. Enable the Auto Enable new repositories option for the github org. Delete a repo which is not CLA enabled and add the same repo again.  In EasyCLA UI, the  repo should be added and cla enabled automatically
4. Add github and select only few repositories while installing CLA App. Enable the Auto Enable new repositories option for the github org. Select few more repos in the EasyCLA bot. In EasyCLA UI, the newly added repos should be added and cla enabled automatically
5. Add github and select only few repositories while installing CLA App. Enable the Auto Enable new repositories option for the github org. Remove selected repo and select same repo again in the EasyCLA bot. In EasyCLA UI, the repo should be added and cla enabled automatically
6. Add github. Enable the Auto Enable new repositories option for the github org. Install EasyCLA App for the github org. All the repos added in the EasyCLA bot should be cla enabled in EasyCLA UI

I am not sure about the impact when repo is renamed/changed from private to public or vice versa

**Comment by makkalot** [comment]
I did some walkthrough on the code, here are my findings : 

* `addGithubOrganization` : looks like the funcitonality to `autoEnable` is there for creation : https://github.com/communitybridge/easycla/blob/master/cla-backend-go/github_organizations/repository.go#L84
* `updateGithubOrganization` : looks like the funcitonality to `autoEnable` is there for creation : https://github.com/communitybridge/easycla/blob/master/cla-backend-go/github_organizations/repository.go#L337
* `GitHubOrgAddedEvent` and `GitHubOrgUpdatedEvent` don't check for `autoEnabled` atm.
* on Python side : currently we handle only the `installation_repositories` event types, this is probably why we don't have the trigger being sent to add those repositories, should be probably listening on `repositories` event type as well : https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#repository
  * the logic about repo having only one cla-group and failing otherwise : https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/github.py#L402
  * we already send notification to project managers about repo being added : https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/github.py#L475

** Implementation Strategy Could Be ** 

* Since this is a functionality which is not working correctly on Python side anyways we can migrate it by  /github/activity calling an endpoint on v4 (which we will create). Something like enableRepositories (accepting a list of repos). This could also become a pattern of retiring the Python side gradually.
* if we don't want to spend the extra time of migration can add the `repositories` event type and use the old logic if works ok.
* Second step would be to update the event handlers for `GitHubOrgAddedEvent` and `GitHubOrgUpdatedEvent`
* Adding functional tests for the feature

**Comment by dealako** [comment]
Is there where we get the new repo callback?  DEV config:

![Screen Shot 2020-10-21 at 3.55.31 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/2e78c8c9-b916-4f8e-80bd-6f4950897ef2)

If so, yes, we can work to migrate this code to golang.  Key points:

- Need to migrate over all existing logic
- If /v4 endpoint, need to review the [API-GW pass-through](https://github.com/LF-Engineering/lfx-api-gw/blob/master/config/gateway.config.yml#L92-L93) that we previously added (this was a placeholder) - no handlers implemented to my knowledge
- Prefer to migrate - must work with EasyCLA v1 and v2 (logic is all the same for this, so not an issue)

**Comment by ashav-github** [comment]
@makkalot @dealako I tested this feature today on Dev env. and it doesn't work. Please find the detail below:

**Scenario:** Add github and select All repositories option while installing CLA App. The Github Org has an existing repo with CLA enforced. Enable the 'Auto Enable New Repositories' option for the github org. Add new repo to the github org. In EasyCLA UI, the new repo should be added and cla enabled automatically

**Issue Observed:** The newly added repo is listed on EasyCLA UI however, CLA is not enabled automatically. 

![Screenshot from 2020-11-18 20-00-39.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/6c0ed719-ff4e-410a-a153-102d91b6c004)

**Test Data:** Below is the test data I used for testing-

- CLA Group: asha-foundation-clagrp2
- GitHub organization: ashav-test-devorg1
- Newly Added Repositories: devorg1-repo2, devorg1-repo3, devorg1-repo4, devorg1-repo5

**Comment by manishv09** [comment]
IT is working fine for me, please refer screencast for details as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/9df79eb1-c95c-48f6-8fd5-33c722d07c1e)[https://app.zenhub.com/files/194341141/213953ba-aafb-47c4-bdc4-1f155c3b5050/download](https://app.zenhub.com/files/194341141/213953ba-aafb-47c4-bdc4-1f155c3b5050/download)

**Comment by manishv09** [comment]
Discussed with @pranab-bajpai  and verified, hence closing the issue.
