### ISSUE TITLE
Open LF Login page new tab and preserve the contributor console session so that user can return to it

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2288]
After this screen save the contributor console session and open new tab for LF Login. As discussed in the movie on slack, if a user has no LFID and they go on to create the whole contributor session is lost. 

![image](https://user-images.githubusercontent.com/57362064/101591143-6ca9e400-39b1-11eb-9edc-d886c58ffc49.png)

**Comment by amolsontakke3576** [comment]
@pranab-bajpai I have tested and looked like the issue is from LF login itself and below is the explanation.

1. When contributor successfully sign in on LF page it is redirected to the `https://easycla.dev.communitybridge.org/#/auth` (Expected behavior)
2. When contributor create a new account on LF page and verified his email then it is redirected to the `https://easycla.dev.communitybridge.org/#` (incorrect behavior)
As per the configuration, it should be redirected to the `https://easycla.dev.communitybridge.org/#/auth`

**Comment by amolsontakke3576** [comment]
@pranab-bajpai FYI : On incognito window (private window) session persist only in the current tab and not in another tab due to some limitation of new auth0. we are working on it but tickets are ( [2056](https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2056), [2057](https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2057) ) in a blocked state due to some technical issue.

**Comment by wanyaland** [comment]
Verified and tested by creating new LFID and session is maintained
