### ISSUE TITLE
Steve's Feedback - Anything that is a valid domain name or subdomain name under internet domain name rules should be permitted while adding new org during CCLA flow

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2365]
*Reported by Steve:*

Tier1 - 1C(1): When creating a new company, the company website validation rules still appear to be inconsistent with what is a valid domain or subdomain name. 

For example, “Scorp.example.com” is permitted and “ex-ample.com” is permitted, but “Scorp.ex-ample.com” is flagged as invalid. 

Expected Result: Anything that is a valid domain name or subdomain name under internet domain name rules should be permitted.

**Comment by vinod-kadam** [comment]
Root cause of the issue as updated by @amolsontakke3576 : CLA was using the regex as it was being used by Org Service however later Org Service was updated to use a different regex which was not corresponding changed on CLA side.
Old Regex : ^((http|https):\/\/)?(www.)?[a-zA-Z0-9-]+(\.[a-zA-Z]{2,}){1,3}(#?\/?[a-zA-Z0-9#-]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$
New Regex :  ^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$

**Comment by manishv09** [comment]
Validated today from the list of Domain names shared by Pranab and found working fine on staging environment.
Please find attached list of Domain names and validation screencast for more reference.[https://app.zenhub.com/files/194341141/dbbd5eb2-78f2-4be5-949c-6e33a218cde4/download](https://app.zenhub.com/files/194341141/dbbd5eb2-78f2-4be5-949c-6e33a218cde4/download)[https://app.zenhub.com/files/194341141/06c1871a-97d5-4e70-842b-b312c6a750dd/download](https://app.zenhub.com/files/194341141/06c1871a-97d5-4e70-842b-b312c6a750dd/download)
