### ISSUE TITLE
Identify the EasyCLA Swagger Regex for the Gerrit Name - update to match the PCC regex

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2393]
Identify the EasyCLA Swagger Regex for the Gerrit Name. Update to match the PCC regex.
PCC regex is ^[\w\p{L}][\w\s\p{L}()[]\.\,+-_]{1,99}$     (allowed characters are: starts with alphanumeric, followed by alphanumeric, parentheses, brackets, period, comma, plus, minus, and underscore characters, min length 1, max length 99).

Note: this ticket was created out of LFX-2987.

**Comment by wanyaland** [comment]
Merged changes to dev

**Comment by manishv09** [comment]
Verified today and found not working for the combination "Two){Swagger},gerrit.+-_Max" I am trying to use on Add Gerrit Org 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/9ae6e73c-5ae1-4633-b8d1-0fd5a0ff9b06)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/74745ad1-939f-4ba4-add3-57226b59e498)

**Comment by vinod-kadam** [comment]
Available on Dev env for QA testing.

**Comment by thakurveerendras** [comment]
Issue is tested on DEV environment with below combination & found that issue is fixed as expected & now Gerrit is added properly, So making issue status to QA-Done

Gerrit Instance Name : **Two){Swagger},gerrit.+-_Max**
Gerrit Instance URL : **gerrit.linuxfoundation.org**
ICLA Group ID : **1626**
CCLA Group ID: **1627**
projectSfid: a096s0000003xugAAA

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/00f4b969-a02e-49b9-9734-a97535cab1e7)
