### ISSUE TITLE
V2 Production Corporate Console v2 - Cannot Sign CCLA as CLA Manager designee or Company Admin

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2426]
## Summary

In production, I am unable to sign the CCLA for the company Test_NDC on either user hwdesignee or hwcm

## Background
After clicking "Review and Sign CCLA" in the corporate console, I am presented with this error. 

![image](https://user-images.githubusercontent.com/46732999/104196951-69f83f80-53f2-11eb-9536-bb744d07321e.png)

**Comment by WillsonHG** [comment]
![image](https://user-images.githubusercontent.com/46732999/104197502-189c8000-53f3-11eb-8d1a-4231a9118ca7.png)

**Comment by WillsonHG** [comment]
![image](https://user-images.githubusercontent.com/46732999/104197589-34a02180-53f3-11eb-82a5-37ac303c7a5e.png)

**Comment by vinod-kadam** [comment]
@WillsonHG , Tejas verified CCLA signing on Dev & Staging & it worked fine.
Please verify on Prod.

**Comment by WillsonHG** [comment]
I cannot sign on production. 
{"data":{"requestCorporateSignature":{"code":200,"message":"Document generated successfully","success":true,"data":{"signatureId":null,"signUrl":null,"__typename":"DocumentSignatureDetails"},"__typename":"RequestCorporateSignatureResult"}}}

![image](https://user-images.githubusercontent.com/46732999/104668931-13fff200-56a7-11eb-8986-4cbdf60236a2.png)

**Comment by WillsonHG** [comment]
I was using user hwmanager2 who was invited by a contributor to create an account to become cla manager and sign the cla.

**Comment by sudhakar-proxima** [comment]
Just a note - 
It would be good to use email id that is not linuxfoundation.org as it's observed that the contact scope will be * and level will be staff. That's unlikely to happen for any organization as user will have only his organization scope.

Having said that, it would be good to clear any stale data for the Test_IT Project & Test_NDC organization from CLA database tables.

**Comment by makkalot** [comment]
How is this endpoint queried ? Because I don't see us sending message "Document generated successfully". Also I see this in the logs : 

![Screenshot 2021-01-15 at 13.59.42.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/5edaf7e1-e587-4d96-8fc4-d9ba27bf26d1)

are we sure we're hitting the correct endpoint, because I see v1 being hit only.

**Comment by makkalot** [comment]
I think the issue is terraform config was not updated with new values :
 
- we still use this : https://github.com/communitybridge/easycla/blob/6d9e21f93a6ec7a944f3d808c4ba238151b13d33/cla-backend-go/config/ssm.go#L181
- but in terraform we pass this : https://github.com/LF-Engineering/lfx-easycla-terraform/blob/964fcb53460a2c7205c60a4ba4090ddb4d984be1/ssm.tf#L131

therefore we get this in the logs when we query requestCorporateSignature endpoint : 

![Screenshot 2021-01-15 at 16.25.43 copy.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/e7267935-1287-4522-aa97-6b1a77f1492c)

**Comment by WillsonHG** [comment]
@sudhakar-proxima  thanks for the suggestion, yes I should have been using a gmail address. I removed the contractor.lf users from the Test_NDC org and tried everything again with gmail emails. I observed no change in behaviours. There was a duplicate entry for the organization in the database, so I did remove the older entry, but I observed nothing else to clean up in the database.

**Comment by WillsonHG** [comment]
this has now been resolved in production
