### ISSUE TITLE
Newly added Signing Entity Name not appearing on Docusign for the user 

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2455]
Newly added Signing Entity Name not appearing on Docusign for the user (DEV Environment)
Steps to Reproduce:
Precondition:
1. User has existing organization on SDFC (Swiggy.com)
2. User navigates from corporator console and add new signing Entity name
3. click on porceed to corporate console to sign CCLA
4. User hit start signing process on corporate console to navigate to docusign

Expected Newly added signing entity name should be displayed to the user on docusign

Actual: Newly added signing entity name not be displayed to the user on docusign and sdfc also not updated with newly added signing entity name
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/14bf6fba-6365-4c58-875b-42678cc59456)

**Comment by manishv09** [comment]
@makkalot As discussed over evening standup, please find the required details as follows:
0017c00000lMGfoAAG Company name "Tata Chemicals Ltd."
Newly created user for above mentioned company "manishv.tatachem@proximabiz.com"
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b0aca394-f258-40a8-afd8-0fe9777828f4)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b2955c11-a271-46ae-bfcc-6ebf01ecefd7)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/32158258-3c11-49c2-b6f1-812a2a4c2a92)

**Comment by makkalot** [comment]
I can see that 2 company entries are created on EasyCLA side for each of the signing entity name : 

![Screenshot 2021-01-15 at 17.16.10.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/f71dd7af-1715-462d-9664-6ade4c7c56b5)

![Screenshot 2021-01-15 at 17.16.23.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/30315b66-e0df-498a-96d2-05b7e372d627)

hwen we click **next** how do we decide which company is going to be selected @dealako @amolsontakke3576 ? Also about adding non-existing signing entity names, should we also update the org service about it ? What's the expected behaviour ?

**Comment by makkalot** [comment]
Just to add the findings here related to the issue, the user gets associated randomly with company during requestCorporateSignature (because we query via externalCompanyID) : https://github.com/communitybridge/easycla/blob/main/cla-backend-go/v2/sign/service.go#L132

![Screenshot 2021-01-18 at 17.48.16.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/957cd295-53e6-4d66-8e85-ba09c16ea73c)

![Screenshot 2021-01-18 at 17.48.42.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/8ef5478c-94d7-4db2-9640-994e993fa155)

![Screenshot 2021-01-19 at 18.00.36.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/19e51a62-f02c-4003-bc4b-c6a01d11eb86)

in the screenshots above as it's seen the user was expecting to see `Mozilla India Inc new` in docusign but as it's seen he was associated with `Mozilla India Inc` because of that mentioned random behaviour.

As a result we need a way to associate the user with company with correct signing entity before the signing happens.

**Comment by vinod-kadam** [comment]
As discussed by @dealako with @pranab-bajpai  & Sudhakar, support is needed from Corporate Console for this one.
LFX ticket created for change in Corporate Console is as follows:
https://jira.linuxfoundation.org/browse/LFX-3047: Add support for Signing Entity in CCLA in Corporate Console

**Comment by dealako** [comment]
API updates deployed to DEV, STAGING and PROD. Awaiting final updates to v2 Corporate Console before QA can review final product.

**Comment by manishv09** [comment]
Verified today on staging environment and found user is able to register new user and for that new user the signing entity name is appearing correct on docusign. Please attached video for more details.

https://images.zenhubusercontent.com/194341141/d9bd02a4-cc4a-4849-89df-2b435ea8e270/bug2455_25012021.mp4
