### ISSUE TITLE
Organization Name field remains disabled for organization which is neither present in SDFC nor Clearbit on staging environment while creating new organization

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2460]
Organization Name field remains disabled for organization which is neither present in SDFC nor Clearbit on staging environment while creating new organization
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/75009749-2a91-487f-b9e0-03d391d124f0)

**Comment by amolsontakke3576** [comment]
@vinod-kadam @manishv09 @wanyaland 
Look like the issue is with the lookup endpoint as the `Name` field is missing in response to given websiteURL

Request URL: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/lookup?websiteName=www.wazirx.com
Request Method: GET
Status Code: 200

Response
```
{
  "Employees": "30",
  "Industry": "Diversified Financials",
  "Link": "wazirx.com",
  "Sector": "Financials",
  "Source": "clearbit",
  "signingEntityNames": null
}
```

**Comment by makkalot** [comment]
Looks like this is working fine on dev, maybe something wasn't deployed on staging.
[Uploading... Screenshot 2021-01-15 at 14.57.03.png]

**Comment by manishv09** [comment]
Verified today on staging environment and found working fine. Please find attached screen cast for your reference.
[Uploading... Orgsearch&Autofill-18012021.mp4]
