### ISSUE TITLE
Intermittent Issue: Roles is not assigned to the newly created user when he navigated to corporate console post verifying email and roles setting is complete 

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2463]
Roles is not assigned to the newly created user when he navigated to corporate console post verifying email and roles setting is complete while the account is created in SDFC
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/8d2cf42f-f1e3-4106-a7b0-733e0eb81c9f)

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/91c0aee4-5f8e-469e-bbba-5e29f56eadfd)

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/8382e915-8e56-4dcf-9b6c-ad868112ffb7)

**Comment by vinod-kadam** [comment]
Manish tried 8 times and it didn't worked for 2 times.
Veerendra tried 5 times & it worked for him all 5 times.

**Comment by ashav-github** [comment]
Today I observed this issue again. Still I don't have confirmed steps to reproduce but this is what I tried today:

1. Create a PR, click on 'Not Covered', select CCLA, go to Create New Org., enter a new org. which doesn't exist on sfdc and clearbit.

2. Complete the flow till creating new LFID. 
3. Before verifying the email clear the browser cache after step2 and open a new fresh browser, open your email and verify email

Actual Result: It says 'This portal is only available for corporate users'

**Comment by vinod-kadam** [comment]
Manish/Tejas/Veerendra tried around 10/2/1 times respectively on Staging & it worked fine. So, marking it as QA Done; however we will keep a watch on it.

**Comment by vinod-kadam** [comment]
Upon failure to do cla manager designee settings, it was discussed & implemented to show the following message with Retry option.
"Initial CLA Manager settings could not be assigned. Please click on Retry to allow platform more time to assign settings. Otherwise you can file a support ticket. Once support ticket is resolved, you will be able to proceed with the CLA workflow.
However, as the original issue has been fixed (QA tried it around 10-11 times), it is not possible to test this one. If the original issue get reproduce then we will test it.
