### ISSUE TITLE
Change the text for coverageType from to match "GitHub Username" instead of "Github ID"

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2470]
Change the text for coverageType from to match "GitHub Username" instead of "Github ID"

Note: this is in reference to ticket https://jira.linuxfoundation.org/browse/LFX-3035. The above change couldn't be done through LFX-3035 as it needed a change from backend so this ticket has been created to take care of it.

**Comment by dealako** [comment]
Reviewed and updated public references of Github to GitHub.

**Comment by dealako** [comment]
https://github.com/communitybridge/easycla/pull/2490

**Comment by vinod-kadam** [comment]
Deployed to Dev.

**Comment by thakurveerendras** [comment]
Issue is tested on dev environment & found that "**GitHub Username**" text appears instead of "**Github ID**"  as expected and also checked "**GitHub**" string appears  instead of "**Github**". So making issue status to QA-done.

Refer screenshot for more details 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/31c607cc-6231-4eed-a712-8a5779ece6fc)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/e394a92c-c24f-48fd-9732-61f990892afd)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/32902398-ec03-4f9f-ae74-b9b88bbdffd2)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0827d3ed-5cf7-4a88-80d2-9a305434d48e)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b7c8a0a2-6fdc-477a-8052-2650e2c5b1c3)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/925bffe7-35aa-4e80-9ae2-998c3b94b368)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0d92364c-55f2-41a2-a25d-3916aba92f5a)

**Comment by dealako** [comment]
Closing this ticket now that QA is complete.
