### ISSUE TITLE
Update PR comment when previously-failed PR subsequently passes CLA check

### ISSUE THREAD

**Issue by dfawley** [communitybridge/easycla#269]
**Summary**

Post comment when previously-denied user accepts CLAs.

**Background**

See https://github.com/grpc/grpc-go/pull/3084.  User had not signed CLAs.  A (useful) message was posted indicating this.  When user *did* sign CLAs, there was no further update, but the bot's status was green.  This is confusing for maintainers, because it appears like a failure of the CLA tool: either the first message was in error, or, worse, the contributor has NOT signed the CLAs, yet the bot is still passing.

The mention in [this comment](https://github.com/grpc/grpc-go/pull/3084#issuecomment-540091788) that grpc maintainers didn't want the update was in regards to users that were *already* OK when the PR was first created.  We still wouldn't want messages in these cases.  Only after the bot has posted a comment indicating the CLAs were denied would we want an update.

**User Story**

As a maintainer, I would like a message when a previously-denied contributor accepts the CLAs in order to avoid the confusion described above.

cc @jpalmerLinuxFoundation @ejona86 @easwars

**Comment by jpalmerLinuxFoundation** [comment]
**Summary**

Describe the feature - a clear and concise description of what the feature is.

**Background**

Provide context to the issue - provide steps to indicate how this feature would be realized, such as:
1. Go to a PR where the EasyCLA check has failed
2. Click on the link to sign the CLA
3. Complete the CLA signing
4. Return to PR
5. [Change] If and only if the PR has a CLA Not Signed comment and the status of the CLA check is updated to Signed, then update the comment to say CLA Signed

If the CLA check passes for the PR originally, do NOT post any comment to the PR regarding CLA status

**Target Scenario:**
1. CLA check Fails, CLA Not Signed comment posted 
2. Contributor(s) sign the CLA and CLA check Passes for the same PR that failed
3. Update the Comment to CLA Signed

No Comment Scenario (most common)
1. CLA check passes when PR is opened, do NOT post comment

**User Story**
As a maintainer, I need the CLA comment to match the status of the PR so that when reviewed later it doesn't cause concern or confusion.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, probably needs some clarification, so let's discuss. There was a nuance here that I don't think we considered when we acquiest to CNCF for gRPC changes.

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, I think I'd like to increase the priority of this issue. The confusion this appears to cause is consistently requiring me to intervene.

**Comment by dealako** [comment]
Changes pushed to DEV. Awaiting QA feedback before pushing to STAGING and PROD.

**Comment by dfawley** [comment]
IIUC the code in #292 is (silently) updating the existing "CLA not signed" comment to say it is signed.  While this is certainly an improvement over today's behavior, it would be preferable to add a new comment indicating the change of status.  A new comment would trigger emails to the maintainers -- this notification is important because we may have been waiting on the CLAs to be accepted to either begin reviewing or merge the PR.

**Comment by jpalmerLinuxFoundation** [comment]
Hi, @dfawley,
Part of the reason it works the way it does is due to complains about too many comments flooding maintainers inboxes. I'm hoping to minimize those email notifications. 

Perhaps in version 2, we'll create a setting for PMs to choose the behavior that works for them.

For now, unfortunately, I think we'll need to work with this incremental improvement.

**Comment by dfawley** [comment]
As a data point: the old CLA bot would post a new comment when the CLA status changed, and I never heard anyone complain about it.  I wouldn't consider this event to be spammy; it is meaningful information about a PR's lifecycle.

In any case, posting a new comment is what this FR requested.  Should we reopen this issue (changing the title back to its original version), officially deny the FR, or should I file a new one?

**Comment by dfawley** [comment]
FYI I created #310 to track the original feature request.
