### ISSUE TITLE
Corporate Console doesn't show 'Signed By' and 'Download PDF' icon for a signed CCLA.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2693]
Steps:

1. Login to Corporate console and search for project 'PerfTestFoundation-Child1' 

Actual Result: It shows CCLA is signed but 'Signed By' is empty and no download option shown. 

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/04c526b5-1e76-43f0-ad33-16d86cfa32f6)

Expected Result: 'Signed By' and 'Download' option should be displayed.

**Comment by dealako** [comment]
Sorry, I didn't realize you were going to do detailed functional testing on these generated user accounts. The signature records are missing the CLA Manager entry in the signature record (Signature ACL) as well as the company signatory name/email which signed the DocuSign document. Since we didn't actually sign the DocuSign document, I didn't fill in this field. I will need to go back and randomly assign a user to the existing records.  Additionally, I will need to explicitly set the Download URL in the signature record. V1 actually calculates the PDF path/URL. v2 seems to lack this logic and reads the download URL value from the record.  I will also need to update the generated records to set this value.

Ultimately, the original goal was to just generate a bunch of records.  I will work to make it more realistic by setting the CLA Manager info, signatory name/email, and properly setting the download URL.

**Comment by dealako** [comment]
Ran a migration script to set the CLA Manager name. I chose one randomly from the Staging database.

![Screen Shot 2021-02-22 at 2.33.26 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/768240dd-f749-4f6f-b13e-f28fc640fccb)

**Comment by ashav-github** [comment]
@dealako Ok. Thanks for generating the data, I can see Signed By name and PDF link to download. 
![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/bf1682bd-9a0b-4917-9d7c-9eb5b408c6f6)

However, I am unable to download the pdf and it shows this error as shown below. I believe its because the PDF doesn't exists in reality ? Please confirm. 

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/43bf08e1-5c7c-4d34-a192-e817ddae64a0)

**Comment by vinod-kadam** [comment]
For Document went stale, there is a separate ticket.
So, as updated by @ashav-github  we can mark it as QA Done.
