### ISSUE TITLE
Steve's Feedback: Email sent to an identified CLA Manager (who has LFID) needs a change

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2704]
teve's Feedback document: https://docs.google.com/document/d/1Mq7YWegCg3Zfq_RprtV0e1kaa-Jq0AQDo-wkjucgDj0/edit?ts=603547c9#

Had to modify the email content given by Steve in order to consider multiple projects which can be part of a CLA group.
GitHub when it calls Contributor Console, passes CLAGroupID and not project ID, and when Contributor Console calls CLA backend API it also passes CLAGroupID but not project ID.

Email sent to an identified CLA Manager (who has LFID) should be as follows:

Subject: EasyCLA: Invitation to create LF Login and complete the process of becoming a CLA Manager

Body:
Hello ,

This is a notification email from EasyCLA regarding the project(s): [comma separated list of projects].
We received a request from [USERNAME] ([EMAIL ADDRESS]) to contribute to the above projects on behalf of your organization .
Before the user contribution can be accepted, your organization must sign a Corporate CLA (CCLA). The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.

Please complete the following steps:
1. Login the portal [corporate console link] where you can either sign the CLA for any of the project(s): [comma separated list of linked projects], or send it to an authorized signatory for your company.
2. After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
3. After adding the contributor, please notify them so that they can complete the contribution process.

If you need help or have questions about EasyCLA, you can [read the documentation] or [reach out to us for support].
EasyCLA Support Team

read the documentation & reach out to us for support are links with same name.
Note: in case of foundation level CLA group, show only foundation name.

**Comment by wanyaland** [comment]
@vinod-kadam 
For ```to contribute to the above projects on behalf of your organization``` shouldnt we interject with any like  ```any of the above projects ``` ?

**Comment by vinod-kadam** [comment]
This is deployed to all environments through https://github.com/communitybridge/easycla/releases/tag/v1.0.137

**Comment by manishv09** [comment]
@wanyaland The following changes are missing highlighted in red which are as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/523e379a-47a9-446e-9243-8c44789ea859)

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/c1c650dc-67eb-4718-b565-7cd7038ce432)

**Comment by manishv09** [comment]
Verified on Staging and found the contents are appended now and matching with the changes proposed. Please refer below email content sent to the user.

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project(s): A-LF Networking Fund-Manish-Child001.

We received a request from manishvdy@yahoo.com (manishyahoo09) to contribute to the above projects on behalf of your organization.

Before the user contribution can be accepted, your organization must sign a Corporate CLA (CCLA).The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.

Please complete the following steps:

After login, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for any of the project(s): A-LF Networking Fund-Manish-Child001, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
