### ISSUE TITLE
Change needed in the email sent to designated CLA Manager who doesn't have an LF account

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2730]
From Corporate Console, a user designates someone as CLA Manager however that person doesn’t have an LF Login account. In this case currently, following email is sent to that person.
--------------------------
Subject: Invitation to create LF Login and complete process of becoming CLA Manager with cla-manager-designee role
Body:
Hello Manish Vaidya,
This is a notification email from EasyCLA regarding the Project A-Feb-10 Multi Level Projects and CLA Group A-FEB-10-MULTI-LEVEL-PROJECTS-C5-3113.
User manishv.comprmgr (manishv+comprmgr@proximabiz.com) was trying to add you as a CLA Manager for the Project A-FEB-10 MULTI LEVEL PROJECTS-CHLD005 but was unable to identify your account details in the EasyCLA system. In order to become a CLA Manager for the Project A-FEB-10 MULTI LEVEL PROJECTS-CHLD005, you will need to accept the invite below. Once complete, notify the user manishv.comprmgr and they will be able to add you as a CLA Manager.
Accept Invite
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
--------------------------

Need to change the above email to the following:

--------------------------
Body:
Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the CLA setup and signing process for the organization Proxima.
The user manishv.comprmgr (manishv+comprmgr@proximabiz.com) has identified you as a potential candidate to setup the Corporate CLA for the organization Proxima and the project A-LF Networking Fund-Manish-Child001.

Before the user contribution can be accepted, your organization must sign a Corporate CLA(CCLA). 

Please complete the following steps:
1. Please click on Accept Invite to create your LF Login. This is used to access the EasyCLA CLA Manager console.
2. After login, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for the project: [link to A-LF Networking Fund-Manish-Child001], or send it to an authorized signatory for your company.
3. After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
-------------------------

**Comment by manishv09** [comment]
Verified on Staging and changed text is appearing correct for CLA Manager Designee role.

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the CLA setup and signing process for the organization .The user manishv.comprmgr (manishv+comprmgr@proximabiz.com) has identified you as a potential candidate to setup the Corporate CLA for the organization and the project A-CNCF Structure-

Before the user contribution can be accepted, your organization must sign a Corporate CLA(CCLA).

Please complete the following steps:

Please click on Accept Invite to create your LF Login. This is used to access the EasyCLA CLA Manager console.
After login, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for the project: CNCF-Structure-Child001, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.
