### ISSUE TITLE
Minor change needed in the email sent to designated CLA Manager who has LF Login account 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2731]
Minor change needed in the email sent to designated CLA Manager who has LF Login account 
Currently, following email is sent to designated CLA Manager who has LF Login account
--------------------------
Subject: EasyCLA: Invitation to Sign the Proxima Corporate CLA
Body:
Hello Vinod Kadam,
This is a notification email from EasyCLA regarding the CLA setup and signing process for the organization Proxima.
vinodkps1 vinodk+proximasystems1@proximabiz.com has identified you as a potential candidate to setup the Corporate CLA for the organization Proxima in support of the following project(s):
vinods15foundation_child5
Before the contribution can be accepted, your organization must sign a CLA. Either you or someone whom to designate from your company can login to this portal (https://lfx.staging.platform.linuxfoundation.org) and sign the CLA for this project vinods15foundation_child5
If you are not the CLA Manager, please forward this email to the appropriate person so that they can start the CLA process.
Please notify the user once CLA setup is complete.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
--------------------------

The above email needs a very minor change:  
change the text " Either you or someone whom to designate from your company" to " Either you or someone whom you designate from your company"

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified text change for email body which is as follows:

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the CLA setup and signing process for the organization Proxima.

manishv.comprmgr manishv+comprmgr@proximabiz.com has identified you as a potential candidate to setup the Corporate CLA for the organization Proxima in support of the following project(s):

CNCF-Structure-Child001
Before the contribution can be accepted, your organization must sign a CLA. **Either you or someone whom you designate from your company** can login to this portal (https://lfx.staging.platform.linuxfoundation.org) and sign the CLA for this project CNCF-Structure-Child001

If you are not the CLA Manager, please forward this email to the appropriate person so that they can start the CLA process.

Please notify the user once CLA setup is complete.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
