### ISSUE TITLE
Add labels against ID & email address in the email sent to designated CLA Manager who is identified from Contributor Console    

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2739]
When a contributor identifies initial CLA Manager from Contributor Console then an email is sent that designated CLA Manager.
There are two possible emails sent based on whether the designated CLA Manager has an LF Login account or not.

If designated CLA Manager doesn't have LF Login account that following email is sent:
------------------
Subject: EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager
Body:
Hello Manish jio six,
This is a notification email from EasyCLA regarding the project(s): A-LF Networking Fund-Manish-Child001, A-LF Networking Fund-Manish-Child002, A-LF Networking Fund-Manish-Child003, A-LF Networking Fund-Manish-Child004.
We received a request from manishyahoo09 (manishvdy@yahoo.com) to contribute to any of the above projects on behalf of your organization.
Before the user contribution can be accepted, your organization must sign a Corporate CLA(CCLA). The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.
Please complete the following steps:
Please click on **Accept Invite** to create your LF Login. This is used to access the EasyCLA CLA Manager console.
**After login**, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for any of the project(s): A-LF Networking Fund-Manish-Child001,A-LF Networking Fund-Manish-Child002,A-LF Networking Fund-Manish-Child003,A-LF Networking Fund-Manish-Child004, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
------------------ 

If designated CLA Manager has an LF Login account that following email is sent:
------------------
Subject: EasyCLA: Invitation to Sign the Pinterest Corporate CLA and add to approved list amolsontakke3576
Body:
Hello Amol,
This is a notification email from EasyCLA regarding the project(s): NewOrgChange002.
We received a request from amols@proximabiz.com (amolsontakke3576) to contribute to the above **projects** on behalf of your organization.
Before the user contribution can be accepted, your organization must sign a Corporate CLA (CCLA). The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.
Please complete the following steps:
**After login**, you will be redirected to the portal https://lfx.dev.platform.linuxfoundation.org where you can either sign the CLA for any of the project(s): NewOrgChange002, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team

------------------
The above emails need following changes.
1. Email says "Please click on **Accept Invite** to create your LF Login" but there is no link to accept invite. Can we make Accept Invite clickable so that user can click on it. Similarly "After login" doesn't tell the user where exactly they have to login
2. The comma separated list of projects doesn't have spaces between each project name
3. There are some sentence where there is no space after period and the next sentence starts
4. Instead of giving a generic link like https://lfx.dev.platform.linuxfoundation.org could we change it to project specific link so that the user doesn't have to search for that project
5. The sentence which says "We received a request from ..." doesn't mention tell exactly whether value is GitHub Username & GitHub Email Address. So, need to add label before the value. 
We received a request from GitHub Username: manishyahoo09 (Email Address: manishvdy@yahoo.com)
We received a request from Email Address: amols@proximabiz.com (GitHub Username: amolsontakke3576).
Note: If email address is certainly GitHub Email Address then instead of saying Email Address say GitHub Email Address.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
If User has  LF Login :
Subject: EasyCLA: Invitation to Sign the Reliance Jio Infocomm Limited Corporate CLA and add to approved list manishyahoo09

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project(s): A-LF Networking Fund-Manish-Child001, A-LF Networking Fund-Manish-Child002, A-LF Networking Fund-Manish-Child003, A-LF Networking Fund-Manish-Child004.

We received a request from manishvdy@yahoo.com (manishyahoo09) to contribute to the above projects on behalf of your organization.

Before the user contribution can be accepted, your organization must sign a Corporate CLA (CCLA).The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.

Please complete the following steps:

After login, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for any of the project(s): A-LF Networking Fund-Manish-Child001,A-LF Networking Fund-Manish-Child002,A-LF Networking Fund-Manish-Child003,A-LF Networking Fund-Manish-Child004, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team

**Comment by manishv09** [comment]
If User doesn't have LF Login and coming from Github
Subject: EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager

Hello Manish Paytm Five,

This is a notification email from EasyCLA regarding the project(s): A-Feb-10 Multi Level Projects-CHLD004.

We received a request from GitHub Username: manishyahoo09 (GitHub Email Address: manishvdy@yahoo.com) to contribute to any of the above projects on behalf of your organization .

Before the user contribution can be accepted, your organization must sign a Corporate CLA(CCLA). The requester has stated that you would be the initial CLA Manager for this CCLA, to coordinate the signing of the CCLA and then manage the list of employees who are authorized to contribute.

Please complete the following steps:

Please click on Accept Invite to create your LF Login.This is used to access the EasyCLA CLA Manager console.
After login, you will be redirected to the portal https://lfx.staging.platform.linuxfoundation.org where you can either sign the CLA for any of the project(s): A-Feb-10 Multi Level Projects-CHLD004, or send it to an authorized signatory for your company.
After signing the CLA, you will need to add this contributor to the approved list in the CLA Manager console.
After adding the contributor, please notify them so that they can complete the contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
