### ISSUE TITLE
V1 contributor console - Gerrit - Errors when contributor sends request to cla manager to be approved.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2769]
A user created a ticket for this issue. Their company signed a CCLA but had not added the user to the approved list. The user used the contact form to send the cla manger a notification that they'd like to be approved and ran into issues. They report:

When I click "contact" button nothing happens and when I click somewhere else, the contact form comes and goes very quickly.

This happens on both Chrome and Firefox.

I found this error in Firefox console:
ERROR Error: Uncaught (in promise): TypeError: user.user_emails is null

**Comment by WillsonHG** [comment]
https://github.com/communitybridge/easycla/issues/1670

**Comment by amolsontakke3576** [comment]
@WillsonHG I have gone through the code and looks like either the issue is with cache or in the user record (as per the error mentioned in the ticket user object is null).
I have tested on my side and it is working fine with me.

Can you please share the project and userId or simply a contributor console URL?

**Comment by WillsonHG** [comment]
@amolsontakke3576  the linked ticket with the problem is in my comment. It's a user from Gerrit - check his comment in #1670
