### ISSUE TITLE
EasyCLA GitHub App says Missing CLA Authorization for signed commits with CLA

### ISSUE THREAD

**Issue by porunov** [communitybridge/easycla#3090]
## Summary

Several days ago we noticed that EasyCLA GitHub App now always saying that the commit is not authorized under a signed CLA.
EasyCLA shows status:  `Missing CLA Authorization`.
If trying to follow the links in the comments from EasyCLA they don't work. The return the next response: `{"message": "Internal server error"}`.

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Go to https://github.com/JanusGraph/janusgraph/pull/2731 or https://github.com/JanusGraph/janusgraph/pull/2657
1. Click on 'Please click here to be authorized'.
1. See error `{"message": "Internal server error"}`

## Expected behavior

1. Go to https://github.com/JanusGraph/janusgraph/pull/2731 or https://github.com/JanusGraph/janusgraph/pull/2657
1. Click on 'Please click here to be authorized'.
1. See steps to get authorization.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [X] PROD 
* Browser:
  - [X] Chrome/Brave
  - [X] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by porunov** [comment]
I don't know if that's related to EasyCLA or something else but I see in response headers the next header:
`x-cache | Error from cloudfront` which would mean that it's a problem on `cloudfront` side but I'm not sure.

**Comment by dealako** [comment]
@porunov - two points:
- We observed an issue on Friday where the app did not properly report status (status did not update).  We apologize for the inconvenience. This was due to an indexing issue in our database that caused the process to fail. As a result, PR's that were opened during this time window were blocked since the EasyCLA app did not report status.  This was resolved on Friday.
- While evaluating this issue, we also discovered that the "/easycla" comment is not properly triggering the app to re-evaluate the CLA status in all cases. We are currently investigating this issue. Until we get this resolved, you can close and re-open the PR to force the EasyCLA app to report status.

**Comment by dealako** [comment]
CC: @WillsonHG

**Comment by dealako** [comment]
@porunov this issue should be resolved now.  I see that your PR referenced above passed the CLA authorization/gating and was merged.  Awesome! Thanks for the ticket and for helping us resolve the issue. Closing this ticket.
