### ISSUE TITLE
Committer continues to pass check after leaving whitelisted GH org

### ISSUE THREAD

**Issue by christopherclark** [communitybridge/easycla#332]
When a user is no longer a public member of a whitelisted GH org, they should no longer pass the EasyCLA check (unless they are approved by another method, i.e. email, username, another org).  Currently, if a user leaves a whitelisted org, they will continue to pass future CLA checks.

I discovered this using a now-deleted GH account "testing972", which was a public member of a whitelisted GH org under the company "CFF Migration". After hiding membership in the org, or leaving the org, this account still passes the EasyCLA check on new PRs, which it should not.

**Comment by dealako** [comment]
Confirmed.  When removing user from the GH Org whitelist (or any other whitelist), need to:

**Comment by pranab-bajpai** [comment]
@dealako this issue takes care of the deleted contributor use case that we discussed with @swinslow and @mkdolan on 12/2. I think we should prioritize this and fix it soon.

**Comment by dealako** [comment]
Ultimately, this issue is about keeping the GitHub Organization team members/permissions in sync with the EasyCLA system.

If we were to implement this, several things need to happen:

1. We need to adjust the EasyCLA bot permissions to allow the EasyCLA system to query the GitHub Org teams/users (GH Org -> Permissions and Events -> Repository permissions -> Administration) to determine if a given user was removed.  Secondly, I didn't see a webhook callback option to be notified when GitHub Org Owners add/update/delete users from their organization. As a result, the EasyCLA system would not be automatically notified.  The alternative approach is to periodically check and sync (scheduled activity/agent).
1. If/when we change the EasyCLA bot permissions, Organizations and Repositories with the EasyCLA bot already installed would need to re-verify the application.  This may (will?) introduce tech support issues as repo owners would need to re-verify.
1. Three pieces of information need to be resolved to determine if we should remove the authorization for the user:
   1. GH Org team member (verify the user has been removed)
   2. EasyCLA Project/Company whitelist (review whitelist, the user in an email whitelist also?),
   1) EasyCLA signature records (remove the employee record when appropriate)

**Comment by dealako** [comment]
@wanyaland, after speaking with @christopherclark I have a new thought about this issue.

Can you review the flow that checks the signatures for pass/fail. As we walk through the approval checks, the last step we review is the GH Org Whitelist. Before we pass this final step, we can add an API call back to GH to the organization and query to see if the user is indeed still part of the organization. If so, then we continue to pass the check. if not, we should fail this check and remove the user's CCLA signature record (as part of cleanup).

Please review this piece of code - which, I think is only used during the contributor affiliation/employee confirmation step: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/dynamo_models.py#L1612-L1632

and this piece of code:
lookup_github_organizations() function - https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/utils.py#L1167-L1175


It initially looks like we're doing the correct thing - please verify.

But, we need to remove the user's signature record (which would disallow their ability to contribute code) if the user:

1. has an existing CCLA employee signature (they previously affiliated with a company) and we passed the GH checks.
2. fails the 1) domain check, 2) email check, 3) github username check
3. user is no longer in one of the configure GH Org whitelist

Elsewhere in the code (need to find the link for you), we scan for the user's CCLA Employee signature.  When we find it and before we approve/pass the check, we'll need to add a similar API call to GH Org to confirm everything (if they were whitelisted for the org).  This may be tricky as the code currently only checks for a CCLA employee signature record (and doesn't re-verify the whitelist details - those were evaluated when they setup their corporate contributor affiliation).

**Comment by wanyaland** [comment]
@dealako After reviewing the flow, the whitelist check and github org check are working quite well and we would just need to refactor the CCLA employee check, that is https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/utils.py#L611-L612 , calling up the  user whitelist check to satisfy the 3 checks youd listed and then if signature exists just deleting it or returning false for ccla_check. That work around would also cater for GH API call

**Comment by dealako** [comment]
Reviewed PR and merged. Let's test and validate further in DEV and STAGING.

**Comment by wanyaland** [comment]
> Reviewed PR and merged. Let's test and validate further in DEV and STAGING.

Cool

**Comment by christopherclark** [comment]
Thank you @dealako and @wanyaland !

**Comment by pranab-bajpai** [comment]
@nirupamav please verify this fix
