### ISSUE TITLE
Landing page doesn't render properly for all window sizes

### ISSUE THREAD

**Issue by christopherclark** [communitybridge/easycla#341]
The initial landing page could use some responsivity tweaks. The footer bar obstructs the two buttons depending on browser window sizing.  Not at all a high priority but I thought I'd mention it!

Screenshots attached.   
<img width="1364" alt="Good" src="https://user-images.githubusercontent.com/11550052/68707621-ee2d0980-0546-11ea-960e-6926f3c9fc29.png">
<img width="1280" alt="Bad" src="https://user-images.githubusercontent.com/11550052/68707631-f4bb8100-0546-11ea-9fcf-8f216efaeae0.png">
<img width="639" alt="Ugly" src="https://user-images.githubusercontent.com/11550052/68707640-fa18cb80-0546-11ea-900d-fb05e05d17d1.png">

**Comment by nirupamav** [comment]
Verified in Chrome, Firefox and IE that Corporate Console renders properly in different window sizes

**Comment by nirupamav** [comment]
**Issue is reproducible again and hence reopening the ticket**

![image](https://user-images.githubusercontent.com/60865903/78800688-5b02dd80-79d9-11ea-8e31-72bec46c9d72.png)

![image](https://user-images.githubusercontent.com/60865903/78800755-6f46da80-79d9-11ea-8e58-e5289ecb8403.png)


**After clicking on Individual Open CLA button is not visible.**
![image](https://user-images.githubusercontent.com/60865903/78800836-8be31280-79d9-11ea-99c5-29873999567a.png)

**Open CLA button can be seen in Full screen. F11**
![image](https://user-images.githubusercontent.com/60865903/78800945-af0dc200-79d9-11ea-82c9-637d022cd3d1.png)

**Comment by amolsontakke3576** [comment]
@nirupamav  It is similar to the issue #721. which was fixed and I raise the PR.

**Comment by nirupamav** [comment]
**Observed that the issue is fixed**

**_When project name is too long_**
![image](https://user-images.githubusercontent.com/60865903/78864838-1b300a80-7a5a-11ea-9414-8318ed73633b.png)

![image](https://user-images.githubusercontent.com/60865903/78864852-26833600-7a5a-11ea-86f5-dc7387c383b1.png)

**_When project name length is short_**
![image](https://user-images.githubusercontent.com/60865903/78864933-57636b00-7a5a-11ea-8802-c4b666257022.png)

![image](https://user-images.githubusercontent.com/60865903/78864967-664a1d80-7a5a-11ea-97b8-bb84999a9bb1.png)
