### ISSUE TITLE
Don't require committers to authorize the EasyCLA app

### ISSUE THREAD

**Issue by christopherclark** [communitybridge/easycla#349]
The GitHub API [users endpoint](https://api.github.com/users) publicly provides a GH user's email address and organizations. At present, a committer must initially authorize the EasyCLA app, and select their company.  I don't believe that authorization is necessary to check on whether a user is covered by a CLA, given that all relevant information is already retrievable from the GitHub API, publicly. 

If this entire authorization process were eliminated, and was replaced by a call to the GitHub API for user info (every time a PR is opened) crosschecked with existing CLA whitelists, it could:
-  save new committers several steps.
- solve [ issue 332](https://github.com/communitybridge/easycla/issues/332), as a new API would be made at every PR.  
- decrease the complexity/footprint of the EasyCLA app

This may be a significant refactor, but one more of subtraction than addition I'd think. I'd be happy to have a quick call to discuss this sometime.

**Comment by dealako** [comment]
> initially authorize the EasyCLA app

Currently, the GH auth flow which allows the EasyCLA system to extract the user's GH ID and username.  Need to confirm.  I agree that we could refactor the flow to pull the user info via an API call - which we do in other places of the code.

**Comment by dealako** [comment]
@prasannamahajan wrote:

Currently, we use GitHub authorization on the contributor console for the following reasons:
1) fetch user details.
	(possible to do it using GitHub public API. but it will only show public information and GitHub public API are rate limited 60 requests/hour)
2) When contributor associates himself with the company we need GitHub auth for authentication. Otherwise, anyone can associate anyone with any company.
We can remove GitHub authorization only when we remove employee association with the company. If we don't want to remove it then we should not remove GitHub auth.
Technically it is possible to remove GitHub auth. It can be done by changing the flow in which we check GitHub whitelist.

Current flow to pass cla check:
1. check icla
2. check associated companyID of user from users table.
3. check employee signature. 
if we modify this flow to
1. check icla
2. check whitelist of every company that has signed ccla for the project. (this query would require more time.)
I would suggest that we should not do this change. What do you think?
Is it legally require the contributor to associate himself with a company ?

**Comment by dealako** [comment]
Great feedback @prasannamahajan 

Key Points:

- Authenticating the user via GH will allow us to positively identify the user. Because of this, we should continue to leverage the GitHub auth flow.  Otherwise, anyone can spoof who the user is since we currently do not require users to log into the EasyCLA system from the contributor console.
- Authenticating the user via GitHub will allow us to obtain the user’s email - event if it is set to private. Is this correct? Or are we still restricted to their public information? Do you have a reference document or specification for this?

> I would suggest that we should not do this change. What do you think?
Agree
> Is it legally require the contributor to associate himself with the company ?
I’m not a lawyer, but this is the whole idea of verifying you are part of a given company.

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
