### ISSUE TITLE
Corporate CLA list of Employee Acknowledgements has missing names

### ISSUE THREAD

**Issue by aweisberg** [communitybridge/easycla#360]
Which names don't show up is a bit random. Some names for people who have signed recently won't show up no matter how many times I refresh.

![image](https://user-images.githubusercontent.com/1047741/69388659-ad946500-0c97-11ea-90f5-aa01e34b58ed.png)

**Comment by dealako** [comment]
Let's keep this issue open. I believe we are limited to what is available from the GH auth flow (GH -> EasyCLA - only able to see GH user profile information that the user as made public) which is where we pick up the user info.  We need to confirm.

**Comment by aweisberg** [comment]
Displaying only the the GH username is fine. The problem I have right now is that people complain that it's not working (usually because the bot doesn't update PRs when the CLA is signed) and I can't tell if they have successfully signed the CLA.

**Comment by dealako** [comment]
@aweisberg if you have an issue with the EasyCLA bot not passing due to a missing signature, then [please open a ticket]((https://jira.linuxfoundation.org/servicedesk/customer/portal/4) with our support desk and we can help track it down. Currently the tool does not record user names from GH if it's not made public - so the table column will be empty :-(

**Comment by dealako** [comment]
Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
