### ISSUE TITLE
CCLA Manager can see all projects and whitelist all projects associated with their company

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#383]
## Summary

A CCLA Manager can see all projects and whitelist all projects associated with their company.

## Background

The current implementation of the system allows *ALL* CCLA Managers of the company (e.g. the users defined in the `company_acl`) to see ALL the projects the company is associated with.  As a result, they can view and manage the company whitelist of a project they are not affiliated with.  The project/company ACL is defined in the CCLA signature record `signature_acl` column. This ticket is to adjust the corporate console UX page permissions to prevent CCLA Managers from viewing and managing projects they are not associated with.

## Expected behavior

A CCLA Manager should be able to see and whitelist ONLY the projects they are assigned to and not all the projects of that company.

## Use Cases

As a CCLA Manager, I should only see projects that I am affiliated with.

## Acceptance Criteria

Showcase access control restrictions to stakeholders.

## References

N/A

**Comment by dealako** [comment]
Needs a code walk-through on the corporate console permissions. Ultimately, only CLA managers (scope `project_id` + `company_id` + user in the `signature_acl` - should not look at `company_acl`) should be able to perform actions on the console.

**Comment by swinslow** [comment]
Note that the "Use Cases" section in the issue as reported above is incorrect:

> As a CCLA Manager, I should only see projects that I am affiliated with.

It is _not_ a problem if a CLA Manager at a company can _see_ other projects for that company for which they are not a CLA Manager. Read-only access is fine.

The problem is that a CLA Manager should not be able to _edit the whitelist_ or _edit the CLA Manager list_ for a project, unless they are already a CLA Manager for that project, for that company.

The only people who should have write access to a company's whitelist or CLA Manager list for a project are CLA Managers _for that project_.

**Comment by dealako** [comment]
@ngozi-ekekwe Based on our discussions and feedback from @swinslow we will:

**Comment by WillsonHG** [comment]
@dealako I think the above comment is clear, I would only add that this would also apply to the CLA Managers list. 
If user not in signature_acl list, then CLA Manager list is read only.
If user in signature_acl list, then CLA Manager list edit, add, delete is enabled.

**Comment by nirupamav** [comment]
@dealako 
**Tested and observed that CLA Manager who does not have access to the project has Read Only Access. However the whitelisted data and CLA Manager details are not displayed. Is this expected behaviour**

**_CLA Manager who does not have access to Project_**
![image](https://user-images.githubusercontent.com/60865903/78866280-baee9800-7a5c-11ea-8137-c0eb41e966fa.png)

![image](https://user-images.githubusercontent.com/60865903/78866837-c1c9da80-7a5d-11ea-818d-7c7c7052c121.png)


**_Primary CLA Manager of the Project_**
![image](https://user-images.githubusercontent.com/60865903/78866677-7adbe500-7a5d-11ea-8560-86367ef8d2e9.png)

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I have tested the above use case and below are my observation.
1. User can see all the projects but we are showing the `Request Access` link if he is not authorized.
2. All the whitelisted menu (Domain, Email, Github ...) are read-only when user is not authorized.
3. CLA managers list also comes empty from the backend when the user is not authorized.

Do you want any change in the above scenario?

**Comment by dealako** [comment]
The current behavior is ok for now.
