### ISSUE TITLE
Add merge queue GitHub Actions to EasyCLA

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3846]
## Summary

Please add merge queue feature for GitHub https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

## Background

New feature from GitHub merge queue is being enabled for different projects. We need to add this feature to EasyCLA as currently the projects using this feature are getting error from EasyCLA.
Examples:
- https://github.com/kubernetes-sigs/aws-file-cache-csi-driver/actions/runs/4315989850/jobs/7533064820
- https://github.com/trustoverip/hxwg/actions/runs/4028001767/jobs/6924389304

**Comment by WillsonHG** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/46732999/224118466-205dd47e-ffb8-4890-bd71-a3365c5b06cf.png">

**Comment by dealako** [comment]
Additional references:
1. [Managing a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
2. [Merge Group Event](https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group)

**Comment by dealako** [comment]
We must plan the EasyCLA GitHub App/Bot configuration change with the community.  An email notification will be sent to each GitHub Organization Owner which has the EasyCLA App/Bot installed.  Prior to making this change, we should post a brief overview on:

1. Why we are making this change, and why it is necessary
2. What happens if GitHub Organization administrators do NOT approve of this change
3. Explain the feature release timeline for the EasyCLA Merge Queue support

**Comment by Kielek** [comment]
Hi guys, do you have any timeline do changes?

**Comment by nickmango** [comment]
@Kielek yes projection is by next week we shall add this feature

**Comment by thakurveerendras** [comment]
Hello @nickmango 
Kindly check, PR is removed from the merge queue due to no response for a status check 
![image](https://github.com/communitybridge/easycla/assets/75417507/63b42e5f-8358-44a2-a1b2-e7aedf1fb039)
![image](https://github.com/communitybridge/easycla/assets/75417507/3d3db766-d297-4f74-9dd3-9808bf5a50d5)

**Comment by SimenB** [comment]
I'm still seeing that it's waiting - has this been solved?

<img width="901" alt="image" src="https://github.com/communitybridge/easycla/assets/1404810/7a60b554-334f-461d-bcaf-934d2a8daf27">

**Comment by nickmango** [comment]
@SimenB this is pending an official release. Apologies for the confusion. This was done and tested locally however it needs to be communicated and Admin owners alerted about the new feature

**Comment by SimenB** [comment]
Aha 👍 I've disabled merge queue for now - looking forward to enabling it! Is this thread the place to notified about when it's available? 🙂

**Comment by nickmango** [comment]
Once the feature is released email notifications will be sent out to org owners but in addition the ticket shall be updated as well . Pending item is configuration of this feature in prod

**Comment by brianorwhatever** [comment]
I am not an org owner but would like to know when this has been released. Can you please update here as well?
