### ISSUE TITLE
EasyCLA not trigger after add PR on GitHub

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4071]
## Summary

EasyCLA not trigger after add PR

## Background

1. Go to cla enforced GitHub repo
2. Add commit 
3. Add PR
## Actual behavior

EasyCLA Expected — Waiting for status to be reported remain in PR

## Expected behavior
 PR should be gated

PR: https://github.com/SunEarthChildOrg/devRepo01/pull/14
## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/9114f59c-28bd-4668-ac33-f961e29abf6e)

**Comment by thakurveerendras** [comment]
Prod PR: https://github.com/CLATestOrg/VulDetect1/pull/47

**Comment by WillsonHG** [comment]
A fix is being deployed for this, we are currently testing and validating.

**Comment by WillsonHG** [comment]
We have reverted the changes which caused this issue, so it is now resolved in production. If you have an easycla status of 'expected' please comment /easycla in your PR to get the latest status.

We will continue to test the bug that caused the issue in dev.

**Comment by WillsonHG** [comment]
Postmortem:
Recently, we encountered a challenge related to a significant number of commits (approximately 500) from one of our clients. Our primary objective in addressing this issue was to enhance the efficiency of processing a Pull Request with a high volume of commits, prompting us to initiate a hotfix.
This hotfix incorporated the use of a Python package, 'multiprocessor'. Regrettably, this package presented unexpected compatibility issues with our AWS Lambdas. Consequently, the deployment of the hotfix in our production environment disrupted the EasyCLA service.
