### ISSUE TITLE
how to get a easy CLA from presto/presto project?

### ISSUE THREAD

**Issue by mahengyang** [communitybridge/easycla#482]
my account is mahengyang@live.com, I had send a pdf of CLA to  mdolan@linuxfoundation.org, but have not receive any email. I can not pass CLA check in my pull request

**Comment by WillsonHG** [comment]
Hi @mahengyang 
I did respond to your ticket in the support desk this morning, but I'll also put my answer here. 

You have an ICLA signature on file in our system, so it isn't necessary to also email the pdf to mdolan. 

The reason your pull request is not passing the CLA check is because GitHub does not recognize you as the author of your commits. If you notice here https://github.com/prestodb/presto/pull/13936/commits the icon for your commits is blank and there is no github account attached to them.

Github has a help article here https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user about how to fix this issue.

Once this is fixed, you may need to close and reopen that same pr for the cla check to trigger if it doesn't automatically.

Thanks for reaching out,
Heather

**Comment by mahengyang** [comment]
@WillsonHG thk! it is my fault, I had change my local email link to github, Easy CLA now is paased!
