### ISSUE TITLE
Corporate Console: Submit button in "Select Company" Popup is not available as per the note

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#583]
## Background

1. Launch Corporate Console in dev environment
2. Login as CLA manager
3. Click on Get Started under "Associate yourself with a company in Easy CLA" section to add company
4. Below note is displayed in "Select Company" popup. However when we enter a company name which does not exist there is no "Submit" button but can see "ADD Company" button. Also if user has selected a company ,  and then clears company name in the field and enters a company name that does not exist, instead of "Submit" button "JOIN COMPANY" button is displayed
![image](https://user-images.githubusercontent.com/61135378/74653648-a43f6980-51ae-11ea-87ea-b9fe354c5b0d.png)

## Expected behavior
Either the note has to be changed or according to the note "Submit" button should be displayed

**Comment by dealako** [comment]
@pranab-bajpai can you review and provide feedback?

**Comment by nirupamav** [comment]
**_Tested and observed that when field is cleared and when new company is entered, JOIN COMPANY is displayed instead of ADD COMPANY and notification sent message is displayed for company that does not exist. Hence reopening the ticket._**
![image](https://user-images.githubusercontent.com/60865903/77415037-e714e280-6de7-11ea-8514-98162fd973af.png)

![image](https://user-images.githubusercontent.com/60865903/77415119-03188400-6de8-11ea-808c-22dbb81dcd9c.png)



**Verified that JOIN COMPANY is displayed in the note when existing company is selected which is as expected**
![image](https://user-images.githubusercontent.com/60865903/77414422-00695f00-6de7-11ea-92c2-b548b4749c1f.png)

**Comment by nirupamav** [comment]
**_Observed that when field is cleared ADD COMPANY is displayed and when searched with search Criteria JOIN COMPANY is displayed
Observed a corner case issue with below steps. However duplicate company issue is handled and hence closing this ticket_**
1. Search for a company
2. Select the company from dropdown
3. **Now delete few characters and type the name of exsiting company. ADD COMPANY button is displayed**
![image](https://user-images.githubusercontent.com/60865903/77621236-0fc0e780-6f62-11ea-86c4-49b0a72b1397.png)

![image](https://user-images.githubusercontent.com/60865903/77621270-1f403080-6f62-11ea-9371-a5f43cfe216c.png)

4. **However validation for duplicate company exists**
![image](https://user-images.githubusercontent.com/60865903/77621359-47c82a80-6f62-11ea-8d34-6f9b030cdb8f.png)
