### ISSUE TITLE
Usability Issue: User(Contributor) has to scroll down to view all options in the Contributor Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#720]
## Background

1. Launch the github repository (which is configured to sign both CCLA and ICLA)
2. Login as contributor
3. Update any file and create PR
4. Checks fail
5. Click on the link to sign CLA
6. Contributor is redirected to contributor console
7. Observed All options are not completely visible in the console and user has to scroll down to view the options
_Either the logo size should be small to view all options or the options should be displayed from the top_ 

![image](https://user-images.githubusercontent.com/60865903/77284121-f31f7800-6cf3-11ea-99e6-0038cfe5423f.png)

**Comment by dealako** [comment]
@amolsontakke3576 can we optimize the layout?

**Comment by amolsontakke3576** [comment]
Yes we can. I will do.

**Comment by amolsontakke3576** [comment]
@dealako @pranab-bajpai  @nirupamav The problem is with image size. when height of image is more than the width (Vertical Image) that time content will be move below. but when image is horizontal then it's look fine.

PFA: 
![Screenshot from 2020-03-26 19-29-39](https://user-images.githubusercontent.com/56335654/77655292-36017a00-6f98-11ea-9e04-80616ed9a63f.png)

![Screenshot from 2020-03-26 18-47-42](https://user-images.githubusercontent.com/56335654/77654506-2897c000-6f97-11ea-913f-226cc913b916.png)

I have set max height to logo image and now it's look okay but as per my opinion we need to change dashboard UI for contributor console. Please let us know your thought.

![Screenshot from 2020-03-26 19-19-02](https://user-images.githubusercontent.com/56335654/77655135-06527200-6f98-11ea-9371-fdc379f2e51c.png)

**Comment by nirupamav** [comment]
**_Verified that issue is fixed. Verified in Chrome/FF/Edge in windows 10.
But observed that footer is not displayed at the bitton of the page and  there is lot of gap after footer when there is only one option the contributor console and have logged bug #773 to track the issue_**

![image](https://user-images.githubusercontent.com/60865903/77896821-73b31b00-7296-11ea-82b5-0321d15c92b7.png)
