### ISSUE TITLE
UI - Corporate Console - Module Cleanup

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#870]
## Summary

UI - Corporate Console - Module Cleanup.

## Background

- [x] Remove unused modules in the Corporate Console.  Ensure modules are not used or referenced.  Remove HTML, CSS, Module Definition and Typescript logic.
- [x] Remove any unused functions in the cla.services.ts (if any remain)
- [x] Confirm UI still builds and works as expected.

## User Story

As a developer, I want to reduce the UI clutter and not have extra unused files/modules in the source code repository.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
Tested below scenarios and observed bug #940

| Scenario  | Status | Bug | Comments |
| ------------- | ------------- | ------------- | ------------- |
| Launch Corporate Console  | Passed  | | |
| Login to Corporate Console as CLA Manager | Passed | | |
| Select Company popup search functionality | Passed | | |
| Add Company | Passed | | |
| Click on Company and Navigate to Company Details page | Passed | | |
| **Select a Project to Sign a CCLA** popup search functionality | Passed | | |
| Click on SIGN NEW CLA and complete docu sign process | Passed | | |
| Click VIEW MANAGER for a project | Passed | | |
| Search functionality in VIEW MANAGER popup for a project | Passed | | |
| Click on MANAGE APPROVED LIST | Failed | #940 |Observed no action is performed and error in console. Approved List Management and Add/Delete CLA Manager functionality is blocked due to this|
| Request to Join Company | Passed | | |
| Request to Join Pending info for company that has not been approved for CLA Manager request | Passed | | |
| Accept Join Company Request | Passed | | |
| Decline Join Company Request | Passed | | |
| Click on SIGN NEW CLA and send notification to signatory. Access the docusign from email and complete docusign bu signatory. View the Project for the company Corporate console | Passed | | |
| Pending Whitelist Count when whitelisting is requested by employee | Passed | | |
| EasyCLA Documentation link from header | Passed | | |
| Get Help link from footer | Passed | | |
| Signout from menu | Passed | | |
