### ISSUE TITLE
Migrate gerrit api to golang

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#899]
## Summary

Several of the APIs used by the Project management console need migration to golang to support 1) consolidated queries and 2) LFX V2 API integration.

## Background

Migrate the following Python APIs to Golang (v3):
POST  /v1/gerrit/<gerritId>
DELETE  /v1/gerrit/

Provide Golang implementation for two endpoints:
- [x] Include these endpoints into the v3 swagger specification, review, and cleanup API endpoint/path as necessary
- [x] Define the request, response, and error models in the swagger specification. Ensure documentation/examples are added to support api-docs readability.
- [x] If possible, when possible, consolidate the API quests into one endpoint (e.g. avoid duplicate/similar endpoints and data models)
- [x] Develop the golang handler to support the new v3 endpoints
- [x] Develop the service handler
- [x] Develop the repository/database handler
- [x] Write v4 swagger specification - provide pass-through to v3 data models
- [x] Develop the golang handler to support the new v4 endpoints
- [x] Add audit events
- [x] Update acs-cli specification to allow queries of data for authenticated users 
 
## User Story

As a developer, I want to optimize the PMC queries.
As a developer, I want to consolidate API requests to the golang backend API.
As a developer, I want to support LFX v2 integration by using golang to invoke the legacy v3 API

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by prasannamahajan** [comment]
ACS Pull Request : https://github.com/LF-Engineering/acs-cli/pull/150

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**_POST ACTION_**
1. **groupdId of ccla is returned to groupDd of icla in the response after adding gerrit instance**
![image](https://user-images.githubusercontent.com/60865903/80941082-16633a00-8dff-11ea-917c-7d99951e64df.png)
2. **Able to add same gerrit instance multiple times from V3 api**
![image](https://user-images.githubusercontent.com/60865903/80941191-6e01a580-8dff-11ea-89f5-d9f7bcc09069.png)
3. **Able to add gerrit instance without gerrit url**
![image](https://user-images.githubusercontent.com/60865903/80941425-0861e900-8e00-11ea-8557-15972818ac6a.png)
4. **When token is expired 500 is returned instead of 401**
![image](https://user-images.githubusercontent.com/60865903/80941492-35ae9700-8e00-11ea-8b29-173681f30c20.png)

**_DELETE ACTION_**
1. **When token is expired 500 is returned instead of 401**
![image](https://user-images.githubusercontent.com/60865903/80941689-b4a3cf80-8e00-11ea-8e4b-08674477a807.png)
2. **200 is returned instead of 204 when gerrit instance is deleted**
![image](https://user-images.githubusercontent.com/60865903/80941730-d604bb80-8e00-11ea-8056-ee7dee4cdd37.png)


**_In UI V1 api is used for adding gerrit instance_**
![image](https://user-images.githubusercontent.com/60865903/80940541-bddf6d00-8dfd-11ea-8fff-f002fd311cf0.png)

**Comment by nirupamav** [comment]
All API issues are fixed. 
Blocked with UI testing

**Comment by nirupamav** [comment]
Testing Blocked due to #2032

**Comment by nirupamav** [comment]
Verified that all issues are fixed. In UI V3 API's are called
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/033611ba-ab52-49bf-ad1e-d7ea357c3dae)
