### ISSUE TITLE
[Staging] All emails show in request allow list on corporate console in all project cla's.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#908]
From the contributor console, a contributor will choose which email they would like their manager to put on the allow list. The corporate console shows every email in the profile in the request access section instead of the one chosen by the contributor. The request will also show in every project the company has signed a cla for.

- [x] whitelist request shows in every project the company has a signed cla for
- [x] whitelist request can be rejected but not approved
- [x] whitelist request shows every email in the contributor's profile and not the one selected through the dialog in the contributor console.

**Comment by dealako** [comment]
Pushing PR to fix item 1

**Comment by dealako** [comment]
item 3 resolved with the recent update. Existing invites in DB will have multiple emails, but moving forward new ones will only have the one selected in the UI.  We will need to purge the Database and cleanup.

**Comment by nirupamav** [comment]
Verified and observed that issue1 and issue3 are solved. Since issue1 was tracked in bug #768, closed the bug

**Issue1**
![image](https://user-images.githubusercontent.com/60865903/80184754-caf3a380-8628-11ea-9f6c-f7fa573a6518.png)

![image](https://user-images.githubusercontent.com/60865903/80184804-e363be00-8628-11ea-9284-5ea52c84e9b3.png)

![image](https://user-images.githubusercontent.com/60865903/80184980-35a4df00-8629-11ea-8aaf-d4a560846cfe.png)

**Issue3**
![image](https://user-images.githubusercontent.com/60865903/80184852-fa0a1500-8628-11ea-9764-0b4e3811a039.png)

![image](https://user-images.githubusercontent.com/60865903/80184958-27ef5980-8629-11ea-8d29-4e1c5e4406e4.png)

**Comment by dealako** [comment]
@nirupamav pushed updates to DEV.

Key point: the DEV environment has filters that prevent us from sending emails to all domains.  I think the linuxfoundation, proxima, and andela domains are all authorized.

**Comment by nirupamav** [comment]
**_Verified in dev environment that CLA Manager is able to accept the Employee approval request. However there are other issues and are tracked in #987, #988, #882_** 
![image](https://user-images.githubusercontent.com/60865903/80342696-37b5aa80-8882-11ea-812e-ad099ce60732.png)


![image](https://user-images.githubusercontent.com/60865903/80346384-443d0180-8888-11ea-929f-afa1f4b34487.png)
